import test from 'node:test';
import assert from 'node:assert/strict';
import {openDatabase} from '../src/db.js';
import {communityMetrics,h2hMetrics} from '../src/community-metrics.js';
import {rebuildHistoricalGameXp,loadXpConfig} from '../src/community-xp.js';

const addPlayer=(db,id,name,username)=>db.prepare("INSERT INTO players(id,name,platform,username,registration_status) VALUES (?,?, 'lichess',?,'historical_unconfirmed')").run(id,name,username);
const addHistoricalGame=(db,{id,white,black,result,playedAt})=>{const raw=JSON.stringify({id});db.prepare("INSERT INTO source_provenance(id,entity_type,source_system,source_table,source_id,source_sha256,raw_json) VALUES (?,?,?,?,?,?,?)").run(`P-${id}`,'game','test','games',id,'0'.repeat(64),raw);db.prepare("INSERT INTO historical_games(id,source_system,source_game_id,played_at,white_player_id,black_player_id,result,identity_status,source_sha256,provenance_id) VALUES (?,'test',?,?,?,?,?,'CONFIRMED_SOURCE_ID',?,?)").run(id,id,playedAt,white,black,result,'0'.repeat(64),`P-${id}`);};

test('community metrics and H2H remain separate from League Points',()=>{const db=openDatabase(':memory:');addPlayer(db,'A','Ana','ana');addPlayer(db,'B','Beto','beto');addHistoricalGame(db,{id:'G1',white:'A',black:'B',result:'1-0',playedAt:'2026-08-09T12:00:00Z'});addHistoricalGame(db,{id:'G2',white:'B',black:'A',result:'1/2-1/2',playedAt:'2026-08-10T12:00:00Z'});const metrics=communityMetrics(db,{now:new Date('2026-08-10T18:00:00Z')}).find(x=>x.playerId==='A');assert.equal(metrics.games7d,2);assert.equal(metrics.wins,1);assert.equal(metrics.draws,1);assert.equal(metrics.currentStreak,2);assert.deepEqual(h2hMetrics(db,'A','B'),{playerA:'A',playerB:'B',total:2,wins:1,draws:1,losses:0,games:[{id:'G1',sourceGameId:'G1',platform:null,url:null,playedAt:'2026-08-09T12:00:00Z',result:'1-0'},{id:'G2',sourceGameId:'G2',platform:null,url:null,playedAt:'2026-08-10T12:00:00Z',result:'1/2-1/2'}]});assert.equal(db.prepare('SELECT COUNT(*) AS n FROM games').get().n,0);db.close();});

test('Community XP reads editable caps and decreases repeated-opponent awards',()=>{const db=openDatabase(':memory:');addPlayer(db,'A','Ana','ana');addPlayer(db,'B','Beto','beto');for(let i=1;i<=7;i+=1)addHistoricalGame(db,{id:`G${i}`,white:'A',black:'B',result:'1-0',playedAt:`2026-08-10T1${i}:00:00Z`});db.prepare("UPDATE community_xp_config SET value_json='3' WHERE key='daily_game_limit'").run();const config=loadXpConfig(db);assert.equal(config.daily_game_limit,3);rebuildHistoricalGameXp(db);const rows=db.prepare("SELECT awarded_xp FROM community_xp_events WHERE player_id='A' ORDER BY occurred_at").all();assert.equal(rows.length,7);assert.ok(rows[0].awarded_xp>rows[1].awarded_xp);assert.equal(rows.slice(3).reduce((sum,x)=>sum+x.awarded_xp,0),0);assert.ok(rows.reduce((sum,x)=>sum+x.awarded_xp,0)<=config.daily_cap);db.close();});
