const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token=localStorage.getItem('hmena_student_session')||'';
let locale=localStorage.getItem('hmena_portal_locale')||null;
let activePortalTab=localStorage.getItem('cis_portal_tab')||'home';
const copy={
  en:{brand:'MY PROGRESS',logout:'Log out',private:'Private access',title:'My Progress',help:'Enter the username and code your coach gave you.',username:'Username',code:'Code',login:'Sign in',subtitle:'A clear path from real games to better chess.',student:'Student',attendance:'Attendance',comprehension:'Comprehension',accounts:'Chess accounts',ratings:'Rating progress',priorities:'Learning priorities',classes:'Upcoming classes',assignments:'Assignments',notes:'Notes shared by your coach',noRatings:'Link Lichess or Chess.com to start tracking rating.',noPriorities:'No learning priorities calculated yet.',noClasses:'No upcoming classes scheduled.',noAssignments:'No pending assignments.',pending:'CIS assessment pending',hello:'Hello',noStudents:'No students are linked to this account.',days:'days tracked',language:'Class language',en:'English',es:'Spanish',bilingual:'Bilingual',ratingAlt:'Rating progress',nextPlan:'Coach-approved next focus',nextPlanEmpty:'Your coach will set the first training focus after the level check.',training:'Training insights',coachInsight:'Coach insight',leaks:'Where points are leaking',mistakePuzzles:'Mistake puzzles',recommendedLesson:'Recommended lesson',noTraining:'Play or link more games to build your training profile.',diagnostic:'CIS 0–800 Assessment',diagnostic1200:'CIS 800–1200 Assessment',diagnosticAdvanced:'CIS Advanced Level Check',startDiagnostic:'Start diagnostic',competitiveFundamentals:'Competitive Fundamentals',ready1200:'Ready for 1200–1600',continueDiagnostic:'Continue diagnostic',question:'Question',answer:'Answer',next:'Next',diagnosticDone:'Diagnostic complete',foundations:'Foundations',development:'Development',gaps:'Skills to reinforce',noGaps:'No gaps detected in this screening.',close:'Close',score:'Score',ready800:'Ready for the 800–1200 diagnostic',placementResult:'Placement result',puzzleInstruction:'Find the best move',selectMove:'Tap a piece, then its destination square.',correctMove:'Correct!',tryAgain:'Try again.',noPuzzles:'No mistake puzzles yet.',openingTrainer:'Opening trainer',openingFocus:'Opening focus',noOpeningData:'Play more linked games to build your opening profile.',openingGames:'games',openingCpl:'opening avg CP loss',openingErrors:'critical opening errors',reports:'Progress reports',noReports:'No progress report has been published yet.',reportSkills:'Skills secured',reportPractice:'Skills in practice',reportRatings:'Rating changes',reportNext:'Next focus'},
  es:{brand:'MI PROGRESO',logout:'Cerrar sesión',private:'Acceso privado',title:'Mi progreso',help:'Ingresa el usuario y código que te dio tu coach.',username:'Usuario',code:'Código',login:'Entrar',subtitle:'Un camino claro desde partidas reales hacia un mejor ajedrez.',student:'Alumno',attendance:'Asistencia',comprehension:'Comprensión',accounts:'Cuentas de ajedrez',ratings:'Progreso de rating',priorities:'Prioridades de aprendizaje',classes:'Próximas clases',assignments:'Tareas',notes:'Notas compartidas por tu coach',noRatings:'Vincula Lichess o Chess.com para empezar a medir tu rating.',noPriorities:'Aún no hay prioridades de aprendizaje calculadas.',noClasses:'No hay próximas clases cargadas.',noAssignments:'No hay tareas pendientes.',pending:'Evaluación CIS pendiente',hello:'Hola',noStudents:'No hay alumnos vinculados a esta cuenta.',days:'días registrados',language:'Idioma de la clase',en:'Inglés',es:'Español',bilingual:'Bilingüe',ratingAlt:'Progreso de rating',nextPlan:'Próximo enfoque aprobado por tu coach',nextPlanEmpty:'Tu coach definirá el primer enfoque de entrenamiento después de la evaluación.',training:'Inteligencia de entrenamiento',coachInsight:'Insight del coach',leaks:'Dónde se escapan los puntos',mistakePuzzles:'Problemas de tus errores',recommendedLesson:'Lección recomendada',noTraining:'Juega o vincula más partidas para construir tu perfil de entrenamiento.',diagnostic:'Evaluación CIS 0–800',diagnostic1200:'Evaluación CIS 800–1200',diagnosticAdvanced:'Evaluación avanzada CIS',startDiagnostic:'Comenzar diagnóstico',competitiveFundamentals:'Fundamentos competitivos',ready1200:'Listo para 1200–1600',continueDiagnostic:'Continuar diagnóstico',question:'Pregunta',answer:'Responder',next:'Siguiente',diagnosticDone:'Diagnóstico completado',foundations:'Fundamentos',development:'Desarrollo',gaps:'Habilidades por reforzar',noGaps:'No se detectaron huecos en este diagnóstico.',close:'Cerrar',score:'Puntuación',ready800:'Listo para el diagnóstico 800–1200',placementResult:'Resultado de colocación',puzzleInstruction:'Encuentra la mejor jugada',selectMove:'Toca una pieza y después su casilla de destino.',correctMove:'¡Correcto!',tryAgain:'Intenta de nuevo.',noPuzzles:'Aún no hay problemas creados desde tus errores.',openingTrainer:'Entrenador de aperturas',openingFocus:'Prioridad de apertura',noOpeningData:'Juega más partidas vinculadas para construir tu perfil de aperturas.',openingGames:'partidas',openingCpl:'pérdida CP promedio en apertura',openingErrors:'errores críticos de apertura',reports:'Reportes de progreso',noReports:'Aún no hay un reporte de progreso publicado.',reportSkills:'Habilidades consolidadas',reportPractice:'Habilidades en práctica',reportRatings:'Cambios de rating',reportNext:'Próximo enfoque'}
};
Object.assign(copy.en,{botArena:'CIS Chess Bot Arena',botHelp:'Pass practical challenges against calibrated CIS bots.',botLocked:'Locked',botPassed:'Passed',botRecommended:'Recommended',botStart:'Start challenge',botLevel:'CIS level',botGame:'Game',botNext:'Next game',botPoints:'Points',botPractical:'Practical strength',botPass:'Challenge passed',botFail:'Challenge not passed',yourColor:'Your color',white:'White',black:'Black'});
Object.assign(copy.es,{botArena:'CIS Chess Bot Arena',botHelp:'Supera retos prácticos contra bots CIS calibrados.',botLocked:'Bloqueado',botPassed:'Aprobado',botRecommended:'Recomendado',botStart:'Comenzar reto',botLevel:'Nivel CIS',botGame:'Partida',botNext:'Siguiente partida',botPoints:'Puntos',botPractical:'Fuerza práctica',botPass:'Reto aprobado',botFail:'Reto no aprobado',yourColor:'Tu color',white:'Blancas',black:'Negras'});
Object.assign(copy.en,{journey:'Chess journey',todayMission:'Today’s mission',currentSnapshot:'Current snapshot',gamesReviewed:'Games reviewed',personalPuzzles:'Personalized puzzles',rapidExperience:'Rapid experience',workOn:'What we’re working on',practiceLab:'Practice Lab',practiceIntro:'Training chosen from real game evidence.',externalPractice:'Lichess practice',openPractice:'Open practice',markDone:'I completed this',reportedDone:'Completed · awaiting coach review',coachConfirmed:'Completed',trackingNote:'External Lichess work is student-reported until coach review.',assessmentMission:'Starting CIS level',assessmentHelp:'A short adaptive assessment uses rating context but still checks the skills that matter.',startLevelCheck:'Start level check',botWarmup:'Optional warm-up',botAssessmentFirst:'Complete the level check to unlock your recommended starting bot. CIS Bot levels run from 200 to 1200.',recentRecord:'Recent analyzed games',nextClass:'Next class',allRatings:'All linked ratings',experience:'games',milestones:'Training path',linked:'Account linked',assessed:'Level assessed',practiceStep:'Practice evidence',coachPlanStep:'Coach plan',openingsTitle:'Opening patterns',technicalHidden:'Technical engine details stay with the coach.',accountConnected:'Connected',submitted:'Submitted'});
Object.assign(copy.es,{journey:'Ruta de ajedrez',todayMission:'Misión de hoy',currentSnapshot:'Estado actual',gamesReviewed:'Partidas revisadas',personalPuzzles:'Problemas personalizados',rapidExperience:'Experiencia Rapid',workOn:'En qué estamos trabajando',practiceLab:'Laboratorio de práctica',practiceIntro:'Entrenamiento elegido desde evidencia real de sus partidas.',externalPractice:'Práctica en Lichess',openPractice:'Abrir práctica',markDone:'Ya lo completé',reportedDone:'Completado · pendiente de revisión',coachConfirmed:'Completado',trackingNote:'La práctica externa de Lichess queda reportada por el alumno hasta revisión del coach.',assessmentMission:'Nivel CIS inicial',assessmentHelp:'Un diagnóstico adaptativo usa el contexto de rating, pero comprueba las habilidades importantes.',startLevelCheck:'Comenzar evaluación',botWarmup:'Calentamiento opcional',botAssessmentFirst:'Completa la evaluación para desbloquear tu bot inicial recomendado. Los niveles CIS Bot van de 200 a 1200.',recentRecord:'Partidas analizadas recientes',nextClass:'Próxima clase',allRatings:'Todos los ratings vinculados',experience:'partidas',milestones:'Ruta de entrenamiento',linked:'Cuenta vinculada',assessed:'Nivel evaluado',practiceStep:'Evidencia de práctica',coachPlanStep:'Plan del coach',openingsTitle:'Patrones de apertura',technicalHidden:'Los detalles técnicos del motor se quedan con el coach.',accountConnected:'Conectada',submitted:'Enviado'});
Object.assign(copy.en,{tacticalLab:'CIS Tactical Lab',tacticalLabIntro:'Verified puzzles selected from current training priorities.',correctThisWeek:'correct this week',cc0Source:'Puzzle source: Lichess CC0 database.',puzzleRating:'CIS Puzzle Rating',accuracy:'Accuracy',streak:'Streak',bestStreak:'Best streak',puzzleDashboard:'Puzzle dashboard',themeAccuracy:'Accuracy by theme',puzzleStreak:'Puzzle Streak',startStreak:'Start streak',streakHelp:'Keep solving; the first miss ends the run.',streakScore:'Streak',streakBest:'Best',streakOver:'Streak over',playAgain:'Play again',puzzleStorm:'Puzzle Storm',startStorm:'Start 3-minute storm',stormHelp:'Solve as many as you can in 3 minutes. Mistakes do not end the run.',stormScore:'Score',stormMistakes:'Mistakes',stormBest:'Best',stormOver:'Time!',stormTime:'Time',puzzleThemes:'Puzzle Themes',themeHelp:'Choose a skill to train with puzzles near your current level.',recommended:'Recommended',themeAvailable:'available',themePractice:'Theme practice'});
Object.assign(copy.es,{tacticalLab:'Laboratorio táctico CIS',tacticalLabIntro:'Problemas verificables seleccionados desde las prioridades actuales.',correctThisWeek:'correctos esta semana',cc0Source:'Fuente de problemas: base CC0 de Lichess.',puzzleRating:'Rating de puzzles CIS',accuracy:'Precisión',streak:'Racha',bestStreak:'Mejor racha',puzzleDashboard:'Dashboard de puzzles',themeAccuracy:'Precisión por tema',puzzleStreak:'Racha de puzzles',startStreak:'Comenzar racha',streakHelp:'Sigue resolviendo; el primer error termina la racha.',streakScore:'Racha',streakBest:'Mejor',streakOver:'Racha terminada',playAgain:'Jugar otra vez',puzzleStorm:'Puzzle Storm',startStorm:'Comenzar storm de 3 minutos',stormHelp:'Resuelve tantos como puedas en 3 minutos. Los errores no terminan la sesión.',stormScore:'Puntos',stormMistakes:'Errores',stormBest:'Mejor',stormOver:'¡Tiempo!',stormTime:'Tiempo',puzzleThemes:'Temas de puzzles',themeHelp:'Elige una habilidad y practica con puzzles cercanos a tu nivel actual.',recommended:'Recomendado',themeAvailable:'disponibles',themePractice:'Práctica por tema'});
Object.assign(copy.en,{answerSaved:'Answer saved',higherCheckpoint:'Started at a higher checkpoint based on verified rating.',continueLevelCheck:'Continue level check',homeTab:'Home',trainTab:'Train',playTab:'Play',progressTab:'Progress',continueTraining:'Continue training',bonusPractice:'Bonus Lichess practice',fromMyGames:'Puzzles from my games',nextClassHome:'Next class',progressSnapshot:'Your progress',seeProgress:'See full progress',startingPoint:'Starting point',unlockStats:'Solve 5 puzzles to unlock accuracy and streak stats.',trackedOn:'games on',win:'win',wins:'wins',loss:'loss',losses:'losses',draw:'draw',draws:'draws'});
Object.assign(copy.es,{answerSaved:'Respuesta guardada',higherCheckpoint:'Empezamos en un punto más avanzado según tu rating verificado.',continueLevelCheck:'Continuar evaluación',homeTab:'Inicio',trainTab:'Entrenar',playTab:'Jugar',progressTab:'Progreso',continueTraining:'Continuar entrenamiento',bonusPractice:'Práctica extra en Lichess',fromMyGames:'Problemas de mis partidas',nextClassHome:'Próxima clase',progressSnapshot:'Tu progreso',seeProgress:'Ver progreso completo',startingPoint:'Punto de inicio',unlockStats:'Resuelve 5 problemas para desbloquear precisión y rachas.',trackedOn:'partidas en',win:'victoria',wins:'victorias',loss:'derrota',losses:'derrotas',draw:'empate',draws:'empates'});
const t=key=>copy[locale||'en']?.[key]||copy.en[key]||key;
const placementLabels={en:{'hmena-0-400':'Foundations · 0–400','hmena-400-800':'Development · 400–800','hmena-800-1200':'Competitive Fundamentals · 800–1200','hmena-1200-1600':'Intermediate · 1200–1600','hmena-1600-2000':'Advanced · 1600–2000','hmena-2000-2300':'Expert · 2000–2300','hmena-2300-2500':'High Performance · 2300–2500'},es:{'hmena-0-400':'Fundamentos · 0–400','hmena-400-800':'Desarrollo · 400–800','hmena-800-1200':'Fundamentos competitivos · 800–1200','hmena-1200-1600':'Intermedio · 1200–1600','hmena-1600-2000':'Avanzado · 1600–2000','hmena-2000-2300':'Experto · 2000–2300','hmena-2300-2500':'Alto rendimiento · 2300–2500'}};
const placementLabel=code=>placementLabels[locale||'en']?.[code]||placementLabels.en[code]||code||'—';
function diagnosticOptionOrder(q){return q.options.map((option,index)=>({option,value:String.fromCharCode(65+index),score:[...(q.id+':'+index)].reduce((h,c)=>((h*33)^c.charCodeAt(0))>>>0,5381)})).sort((a,b)=>a.score-b.score);}
function applyStatic(){if(!locale)return;document.documentElement.lang=locale;document.title=`${t('title')} · CIS Chess`;$('#locale-select').value=locale;$('#brand-sub').textContent=t('brand');$('#logout').textContent=t('logout');$('#login-eyebrow').textContent=t('private');$('#login-title').textContent=t('title');$('#login-help').textContent=t('help');$('#username-label').textContent=t('username');$('#code-label').textContent=t('code');$('#login-button').textContent=t('login');$('#portal-subtitle').textContent=t('subtitle');}

async function api(path,options={}){
  const headers={...(options.body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})};
  const response=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});
  const data=await response.json().catch(()=>({})); if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`); return data;
}
function sparkline(points=[]){
  if(!points.length)return `<div class="empty">${t('noRatings')}</div>`;
  const vals=points.map(p=>Number(p.rating));const min=Math.min(...vals),max=Math.max(...vals),span=Math.max(1,max-min),w=300,h=80,pad=8;
  const coords=vals.map((v,i)=>`${pad+(i*(w-2*pad)/Math.max(1,vals.length-1))},${h-pad-((v-min)/span)*(h-2*pad)}`).join(' ');
  return `<svg class="rating-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(t('ratingAlt'))}"><polyline points="${coords}" fill="none" stroke="currentColor" stroke-width="3" vector-effect="non-scaling-stroke"/></svg>`;
}
function ratingCards(ratings){
  if(!ratings?.series?.length)return `<div class="empty">${t('noRatings')}</div>`;
  return ratings.series.map(s=>{const days=s.points.length;return `<article class="rating-card"><div class="rating-head"><strong>${esc(humanPlatform(s.platform))} · ${esc(String(s.ratingType||'').replace(/^./,c=>c.toUpperCase()))}</strong><span>${s.latestRating} <small>${s.delta>=0?'+':''}${s.delta}</small></span></div>${sparkline(s.points)}<small>${days} ${locale==='es'?(days===1?'día registrado':'días registrados'):(days===1?'day tracked':'days tracked')}</small></article>`;}).join('');
}
const chessPieces={p:'♟',r:'♜',n:'♞',b:'♝',q:'♛',k:'♚',P:'♙',R:'♖',N:'♘',B:'♗',Q:'♕',K:'♔'};
function fenSquares(fen){
  const [placement,turn='w']=String(fen||'').split(/\s+/);const map=new Map();
  (placement||'').split('/').forEach((row,ri)=>{let file=0;for(const ch of row){if(/\d/.test(ch)){file+=Number(ch);continue;}const square=String.fromCharCode(97+file)+(8-ri);map.set(square,ch);file++;}});
  return {map,turn};
}
function puzzleBoard(p,studentId){
  if(!p?.fen)return '';
  const {map,turn}=fenSquares(p.fen),files=turn==='b'?['h','g','f','e','d','c','b','a']:['a','b','c','d','e','f','g','h'],ranks=turn==='b'?[1,2,3,4,5,6,7,8]:[8,7,6,5,4,3,2,1];
  const squares=[];for(const rank of ranks)for(const file of files){const sq=file+rank,piece=map.get(sq)||'',fi=file.charCodeAt(0)-97,light=(fi+rank)%2===1;squares.push(`<button type="button" class="puzzle-square ${light?'light':'dark'}" data-square="${sq}" data-piece="${piece}">${chessPieces[piece]||''}</button>`);}
  return `<article class="mistake-puzzle" data-student-id="${esc(studentId)}" data-puzzle-id="${esc(p.id)}" data-turn="${esc(turn)}"><div class="puzzle-meta"><strong>${esc(p.skillTitle||t('mistakePuzzles'))}</strong><small>${t('puzzleInstruction')}</small></div><div class="puzzle-board">${squares.join('')}</div><small class="puzzle-help">${t('selectMove')}</small><div class="puzzle-result" aria-live="polite"></div></article>`;
}

function practiceBankBoard(p,studentId){
  if(!p?.fen)return '';
  const {map,turn}=fenSquares(p.fen),files=turn==='b'?['h','g','f','e','d','c','b','a']:['a','b','c','d','e','f','g','h'],ranks=turn==='b'?[1,2,3,4,5,6,7,8]:[8,7,6,5,4,3,2,1];
  const squares=[];for(const rank of ranks)for(const file of files){const sq=file+rank,piece=map.get(sq)||'',fi=file.charCodeAt(0)-97,light=(fi+rank)%2===1;squares.push(`<button type="button" class="puzzle-square bank-square ${light?'light':'dark'}" data-square="${sq}" data-piece="${piece}">${chessPieces[piece]||''}</button>`);}
  const theme=(p.themes||[])[0]||'tactics';
  return `<article class="mistake-puzzle bank-puzzle" data-student-id="${esc(studentId)}" data-puzzle-id="${esc(p.id)}" data-turn="${esc(turn)}"><div class="puzzle-meta"><strong>${esc(themeName(theme))}</strong><small>${t('puzzleInstruction')}</small></div><div class="puzzle-board">${squares.join('')}</div><small class="puzzle-help">${t('selectMove')} · ${locale==='es'?'Dificultad':'Difficulty'} ${p.rating??'—'}</small><div class="puzzle-result" aria-live="polite"></div></article>`;
}

const themeLabels={
  en:{fork:'Forks & Double Attacks',pin:'Pins',hangingPiece:'Hanging Pieces',skewer:'Skewers',discoveredAttack:'Discovered Attacks',deflection:'Deflection',backRankMate:'Back-Rank Mate',mateIn2:'Mate in 2',endgame:'Endgames'},
  es:{fork:'Tenedores y ataques dobles',pin:'Clavadas',hangingPiece:'Piezas colgadas',skewer:'Enfiladas',discoveredAttack:'Ataques descubiertos',deflection:'Desviación',backRankMate:'Mate de última fila',mateIn2:'Mate en 2',endgame:'Finales'}
};
const themeName=code=>themeLabels[locale||'en']?.[code]||code;
function practiceThemeCards(s){
  const themes=s.practiceThemes||[];if(!themes.length)return '';
  return `<div class="theme-picker"><div class="theme-picker-head"><div><strong>${t('puzzleThemes')}</strong><small>${t('themeHelp')}</small></div></div><div class="theme-grid">${themes.map(x=>`<button class="theme-card open-theme-practice ${x.recommended?'recommended':''}" data-student-id="${esc(s.id)}" data-theme="${esc(x.theme)}" type="button"><span>${x.recommended?'★':'♟'}</span><div><strong>${esc(themeName(x.theme))}</strong><small>${x.accuracy==null?`${x.total} ${t('themeAvailable')}`:`${x.accuracy}% · ${x.attempts} ${locale==='es'?'intentos':'attempts'}`}${x.recommended?` · ${t('recommended')}`:''}</small></div></button>`).join('')}</div></div>`;
}

function practiceBankBlock(s){
  const bank=s.practiceBank;if(!bank?.puzzles?.length)return `<div class="empty">${t('noPuzzles')}</div>`;
  const cards=bank.puzzles.slice(0,1).map(p=>practiceBankBoard(p,s.id)).join('');
  const p=bank.profile||{},accuracy=p.accuracy==null?'—':`${p.accuracy}%`,history=bank.history||[],themes=bank.themeStats||[];
  const details=history.length>=2?`<details class="puzzle-insights"><summary>${t('puzzleDashboard')}</summary>${sparkline(history.map(x=>({rating:x.ratingAfter})))}</details>`:'';
  const themeDetail=themes.length>=2?`<details class="puzzle-insights"><summary>${t('themeAccuracy')}</summary><div class="puzzle-theme-stats">${themes.slice(0,6).map(x=>`<span><strong>${esc(String(x.theme).replace(/([A-Z])/g,' $1'))}</strong>${x.accuracy}% · ${x.attempts}</span>`).join('')}</div></details>`:'';
  const streak=bank.streakMode||{},themeCards=practiceThemeCards(s),statsReady=Number(p.attempts||0)>=5,correctWeek=s.journey?.activity?.correctPuzzles7d??bank.summary?.correct7d??0,recommended=(s.practiceThemes||[]).find(x=>x.recommended)||(s.practiceThemes||[])[0];
  const continueTraining=recommended?`<button class="btn btn-primary continue-training open-theme-practice" data-student-id="${esc(s.id)}" data-theme="${esc(recommended.theme)}" type="button">${t('continueTraining')} · ${esc(themeName(recommended.theme))}</button>`:'';
  const statCards=statsReady?`<div class="puzzle-dashboard"><article><strong>${p.rating??'—'}</strong><span>${t('puzzleRating')}</span></article><article><strong>${accuracy}</strong><span>${t('accuracy')}</span></article><article><strong>${p.streak??0}</strong><span>${t('streak')}</span></article><article><strong>${streak.best??0}</strong><span>${t('streakBest')}</span></article></div>`:`<div class="puzzle-dashboard puzzle-dashboard-onboarding"><article><strong>${p.rating??'—'}</strong><span>${t('puzzleRating')}</span></article><article class="puzzle-stats-locked"><strong>${Math.max(0,5-Number(p.attempts||0))}</strong><span>${t('unlockStats')}</span></article></div>`;
  return `<div class="tactical-lab-head"><div><strong>${t('tacticalLab')}</strong><small>${t('tacticalLabIntro')}</small></div><span>${correctWeek} ${correctWeek===1?(locale==='es'?'correcto esta semana':'correct this week'):t('correctThisWeek')}</span></div>${statCards}${continueTraining}<div class="puzzle-mode-row"><button class="btn btn-secondary start-puzzle-streak" data-student-id="${esc(s.id)}" type="button">${t('puzzleStreak')} · ${streak.activeRunId?`${t('streakScore')} ${streak.current}`:t('startStreak')}</button><button class="btn btn-secondary start-puzzle-storm" data-student-id="${esc(s.id)}" type="button">${t('puzzleStorm')} · ${(bank.stormMode||{}).activeRunId?`${t('stormScore')} ${(bank.stormMode||{}).current||0}`:t('startStorm')}</button></div>${themeCards}${details}${themeDetail}<small class="practice-source-note">${t('cc0Source')} <a href="https://database.lichess.org/#puzzles" target="_blank" rel="noopener noreferrer">Lichess</a></small>`;
}

let activeStreakStudentId=null,activeStreakRunId=null;
function streakBoard(state){
  const p=state?.puzzle;if(!p?.fen)return `<div class="streak-finish"><h3>${t('streakOver')}</h3><strong>${t('streakScore')} ${state?.score||0}</strong><small>${t('streakBest')} ${state?.best||0}</small><button class="btn btn-primary restart-puzzle-streak" type="button">${t('playAgain')}</button></div>`;
  const {map,turn}=fenSquares(p.fen),files=turn==='b'?['h','g','f','e','d','c','b','a']:['a','b','c','d','e','f','g','h'],ranks=turn==='b'?[1,2,3,4,5,6,7,8]:[8,7,6,5,4,3,2,1],sq=[];
  for(const rank of ranks)for(const file of files){const id=file+rank,piece=map.get(id)||'',fi=file.charCodeAt(0)-97,light=(fi+rank)%2===1;sq.push(`<button type="button" class="puzzle-square streak-square ${light?'light':'dark'}" data-square="${id}" data-piece="${piece}">${chessPieces[piece]||''}</button>`);}
  return `<div class="streak-game" data-turn="${esc(turn)}"><div class="streak-score"><strong>${t('streakScore')} ${state.score||0}</strong><span>${t('streakBest')} ${state.best||0} · ${t('puzzleRating')} ${state.profile?.rating??'—'}</span></div><p>${t('streakHelp')}</p><div class="puzzle-board">${sq.join('')}</div><small class="puzzle-help">${t('selectMove')} · ${locale==='es'?'Dificultad':'Difficulty'} ${p.rating??'—'}</small><div class="puzzle-result streak-result" aria-live="polite"></div></div>`;
}
function renderStreak(state){activeStreakRunId=state.id;$('#streak-title').textContent=t('puzzleStreak');$('#streak-close').textContent=t('close');$('#streak-body').innerHTML=streakBoard(state);}
async function openPuzzleStreak(studentId){activeStreakStudentId=studentId;const state=await api(`../api/portal/students/${encodeURIComponent(studentId)}/practice-streak/start`,{method:'POST',body:JSON.stringify({})});renderStreak(state);if(!$('#streak-dialog').open)$('#streak-dialog').showModal();}

let activeStormStudentId=null,activeStormRunId=null,stormTimer=null,stormRemaining=0;
function stormBoard(state){
  const p=state?.puzzle;if(!p?.fen)return `<div class="streak-finish storm-finish"><h3>${t('stormOver')}</h3><strong>${t('stormScore')} ${state?.score||0}</strong><small>${t('stormMistakes')} ${state?.mistakes||0} · ${t('stormBest')} ${state?.best||0}</small><button class="btn btn-primary restart-puzzle-storm" type="button">${t('playAgain')}</button></div>`;
  const {map,turn}=fenSquares(p.fen),files=turn==='b'?['h','g','f','e','d','c','b','a']:['a','b','c','d','e','f','g','h'],ranks=turn==='b'?[1,2,3,4,5,6,7,8]:[8,7,6,5,4,3,2,1],sq=[];
  for(const rank of ranks)for(const file of files){const id=file+rank,piece=map.get(id)||'',fi=file.charCodeAt(0)-97,light=(fi+rank)%2===1;sq.push(`<button type="button" class="puzzle-square storm-square ${light?'light':'dark'}" data-square="${id}" data-piece="${piece}">${chessPieces[piece]||''}</button>`);}
  return `<div class="storm-game" data-turn="${esc(turn)}"><div class="storm-hud"><strong><span id="storm-clock">${Math.floor((state.remainingSeconds||0)/60)}:${String((state.remainingSeconds||0)%60).padStart(2,'0')}</span></strong><span>${t('stormScore')} ${state.score||0}</span><span>${t('stormMistakes')} ${state.mistakes||0}</span><span>${t('stormBest')} ${state.best||0}</span></div><p>${t('stormHelp')}</p><div class="puzzle-board">${sq.join('')}</div><small class="puzzle-help">${t('selectMove')} · ${locale==='es'?'Dificultad':'Difficulty'} ${p.rating??'—'}</small><div class="puzzle-result storm-result" aria-live="polite"></div></div>`;
}
async function finishStormFromServer(){if(!activeStormStudentId||!activeStormRunId)return;try{const state=await api(`../api/portal/students/${encodeURIComponent(activeStormStudentId)}/practice-storm/${encodeURIComponent(activeStormRunId)}`);renderStorm(state);}catch(e){$('#portal-error').textContent=e.message;}}
function startStormClock(seconds){if(stormTimer)clearInterval(stormTimer);stormRemaining=Math.max(0,Number(seconds)||0);const paint=()=>{const el=$('#storm-clock');if(el)el.textContent=`${Math.floor(stormRemaining/60)}:${String(stormRemaining%60).padStart(2,'0')}`;};paint();if(stormRemaining<=0)return;stormTimer=setInterval(()=>{stormRemaining=Math.max(0,stormRemaining-1);paint();if(stormRemaining<=0){clearInterval(stormTimer);stormTimer=null;finishStormFromServer();}},1000);}
function renderStorm(state,feedback=''){activeStormRunId=state.id;$('#storm-title').textContent=t('puzzleStorm');$('#storm-close').textContent=t('close');$('#storm-body').innerHTML=stormBoard(state);if(feedback&&state.status==='in_progress'){const el=$('#storm-body .storm-result');if(el)el.textContent=feedback;}if(state.status==='in_progress')startStormClock(state.remainingSeconds);else if(stormTimer){clearInterval(stormTimer);stormTimer=null;}}
async function openPuzzleStorm(studentId){activeStormStudentId=studentId;const state=await api(`../api/portal/students/${encodeURIComponent(studentId)}/practice-storm/start`,{method:'POST',body:JSON.stringify({})});renderStorm(state);if(!$('#storm-dialog').open)$('#storm-dialog').showModal();}

let activeThemeStudentId=null,activeThemeCode=null;
function themeTrainerBoard(p){
  if(!p?.fen)return `<div class="empty">${t('noPuzzles')}</div>`;
  const {map,turn}=fenSquares(p.fen),files=turn==='b'?['h','g','f','e','d','c','b','a']:['a','b','c','d','e','f','g','h'],ranks=turn==='b'?[1,2,3,4,5,6,7,8]:[8,7,6,5,4,3,2,1],sq=[];
  for(const rank of ranks)for(const file of files){const id=file+rank,piece=map.get(id)||'',fi=file.charCodeAt(0)-97,light=(fi+rank)%2===1;sq.push(`<button type="button" class="puzzle-square theme-square ${light?'light':'dark'}" data-square="${id}" data-piece="${piece}">${chessPieces[piece]||''}</button>`);}
  return `<div class="theme-game" data-puzzle-id="${esc(p.id)}" data-turn="${esc(turn)}"><div class="theme-trainer-head"><strong>${esc(themeName(activeThemeCode))}</strong><span>${t('puzzleRating')} ${p.rating??'—'}</span></div><div class="puzzle-board">${sq.join('')}</div><small class="puzzle-help">${t('selectMove')}</small><div class="puzzle-result theme-result" aria-live="polite"></div></div>`;
}
async function loadThemePuzzle(){const data=await api(`../api/portal/students/${encodeURIComponent(activeThemeStudentId)}/practice-themes/${encodeURIComponent(activeThemeCode)}/next`);$('#theme-body').innerHTML=themeTrainerBoard(data.puzzle);}
async function openThemePractice(studentId,theme){activeThemeStudentId=studentId;activeThemeCode=theme;$('#theme-title').textContent=`${t('themePractice')} · ${themeName(theme)}`;$('#theme-close').textContent=t('close');await loadThemePuzzle();if(!$('#theme-dialog').open)$('#theme-dialog').showModal();}

function diagnosticBoard(fen){
  if(!fen)return '';
  const {map,turn}=fenSquares(fen),files=turn==='b'?['h','g','f','e','d','c','b','a']:['a','b','c','d','e','f','g','h'],ranks=turn==='b'?[1,2,3,4,5,6,7,8]:[8,7,6,5,4,3,2,1];
  const squares=[];for(const rank of ranks)for(const file of files){const sq=file+rank,piece=map.get(sq)||'',fi=file.charCodeAt(0)-97,light=(fi+rank)%2===1,white=piece&&piece===piece.toUpperCase(),fileLabel=rank===ranks.at(-1)?file:'',rankLabel=file===files[0]?rank:'';squares.push(`<span class="puzzle-square diagnostic-square ${light?'light':'dark'}" data-file-label="${fileLabel}" data-rank-label="${rankLabel}">${piece?`<span class="diagnostic-piece ${white?'piece-white':'piece-black'}">${chessPieces[piece]||''}</span>`:''}</span>`);}
  return `<div class="puzzle-board diagnostic-board" aria-label="Chess position">${squares.join('')}</div>`;
}

function openingTrainerBlock(profile){
  if(!profile?.gamesAnalyzed)return `<div class="empty">${t('noOpeningData')}</div>`;
  const shortName=value=>String(value||'').split(/\s+[0-9]+\.{1,3}/)[0].split(' · ')[0].trim();
  const rows=profile.openings?.slice(0,5).map(o=>`<li><strong>${esc(shortName(o.openingName))}</strong>${o.openingEco?` · ${esc(o.openingEco)}`:''}<br><small>${o.games} ${t('openingGames')} · ${plainRecord(o.wins||0,o.losses||0,o.draws||0)}${Number(o.criticalOpeningErrors||0)>0?` · ${o.criticalOpeningErrors} ${locale==='es'?'errores clave':'key mistakes'}`:''}</small></li>`).join('')||'';
  return `<ul class="family-opening-list">${rows}</ul>`;
}
function reportCards(reports=[]){
  if(!reports.length)return `<div class="empty">${t('noReports')}</div>`;
  const date=v=>new Date(v).toLocaleDateString(locale==='es'?'es-MX':'en-US',{year:'numeric',month:'short',day:'numeric'});
  return reports.map(row=>{const r=row.report||{},mastered=r.skills?.mastered?.slice(0,5).map(x=>esc(x.title)).join(', ')||'—',practicing=r.skills?.practicing?.slice(0,5).map(x=>esc(x.title)).join(', ')||'—';const ratings=(r.ratings||[]).filter(x=>x.delta!==0).slice(0,4).map(x=>`${esc(x.platform)} ${esc(x.ratingType)}: ${x.delta>0?'+':''}${x.delta}`).join(' · ')||'—';const next=r.nextFocus?.lesson?.title||r.nextFocus?.skill?.title||r.noFocus||'—';return `<article class="progress-report-card"><div class="coach-card-head"><strong>${date(row.periodStart)} – ${date(row.periodEnd)}</strong><span class="status-badge">${esc(row.status)}</span></div><p>${esc(r.headline||'')}</p><p><strong>${t('reportSkills')}:</strong> ${mastered}</p><p><strong>${t('reportPractice')}:</strong> ${practicing}</p><p><strong>${t('reportRatings')}:</strong> ${ratings}</p><p><strong>${t('reportNext')}:</strong> ${esc(next)}</p></article>`;}).join('');
}
function familyFindingLabel(item){
  if(item?.skillTitle)return item.skillTitle;
  const labels={
    en:{engine_blunder:'One-move blunders',engine_mistake:'Move accuracy',opening_error:'Opening decisions',missed_forcing_move:'Checks, Captures & Threats',missed_capture:'Hanging pieces',missed_fork:'Forks & double attacks',missed_pin:'Pins',missed_skewer:'Skewers'},
    es:{engine_blunder:'Errores de una jugada',engine_mistake:'Precisión de jugadas',opening_error:'Decisiones de apertura',missed_forcing_move:'Jaques, Capturas y Amenazas',missed_capture:'Piezas colgadas',missed_fork:'Tenedores y ataques dobles',missed_pin:'Clavadas',missed_skewer:'Enfiladas'}
  };
  return labels[locale||'en']?.[item?.findingType]||String(item?.findingType||'').replaceAll('_',' ');
}
function primaryRating(ratings){
  const series=ratings?.series||[];const priority=['rapid','classical','blitz','bullet','daily'];
  return [...series].sort((a,b)=>priority.indexOf(a.ratingType)-priority.indexOf(b.ratingType))[0]||null;
}
function formatClassTime(value){
  if(!value)return '—';const d=new Date(value);if(Number.isNaN(d.getTime()))return value;
  return new Intl.DateTimeFormat(locale==='es'?'es-MX':'en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(d);
}
function plainRecord(wins,losses,draws){const one=(n,a,b)=>`${n} ${n===1?a:b}`;return `${one(wins,t('win'),t('wins'))}, ${one(losses,t('loss'),t('losses'))}, ${one(draws,t('draw'),t('draws'))}`;}
function humanPlatform(value){return String(value||'').toLowerCase()==='chesscom'?'Chess.com':String(value||'').replace(/^./,c=>c.toUpperCase());}
function recentRecord(reviews=[]){const rows=reviews.slice(0,6),wins=rows.filter(x=>x.result==='win').length,losses=rows.filter(x=>x.result==='loss').length,draws=rows.filter(x=>x.result==='draw').length;return {total:rows.length,wins,losses,draws,text:plainRecord(wins,losses,draws)};}
function familyLeaks(training){
  const all=Array.isArray(training?.familyTopLeaks)?training.familyTopLeaks:(training?.topLeaks||[]),preferred=[...all.filter(x=>x.skillTitle),...all.filter(x=>!x.skillTitle)];const seen=new Set(),out=[];
  for(const item of preferred){const label=familyFindingLabel(item);if(!label||seen.has(label))continue;seen.add(label);out.push({...item,label});if(out.length===3)break;}return out;
}
function practiceMissionCards(s){
  const missions=s.practiceMissions||[];
  if(!missions.length)return `<div class="empty">${t('noTraining')}</div>`;
  const render=m=>{const done=m.status==='completed',submitted=m.status==='submitted';return `<article class="practice-mission ${done?'done':''} ${submitted?'submitted':''}"><div class="practice-source"><span>♞</span><small>${t('externalPractice')}</small></div><strong>${esc(m.title)}</strong><p>${esc(m.description)}</p><div class="practice-actions"><a class="btn btn-secondary practice-open" href="${esc(m.url)}" target="_blank" rel="noopener noreferrer">${t('openPractice')} ↗</a>${done?`<span class="mission-status status-ok">✓ ${t('coachConfirmed')}</span>`:submitted?`<span class="mission-status status-warn">✓ ${t('reportedDone')}</span>`:`<button class="btn btn-secondary submit-practice" data-student-id="${esc(s.id)}" data-assignment-id="${esc(m.id)}" type="button">${t('markDone')}</button>`}</div></article>`};
  const primary=render(missions[0]),more=missions.slice(1);
  return `${primary}${more.length?`<details class="compact-more"><summary>${locale==='es'?`${more.length} temas más de Lichess`:`${more.length} more Lichess themes`}</summary><div class="practice-grid compact-practice-grid">${more.map(render).join('')}</div></details>`:''}`;
}
function milestoneStrip(s){
  const j=s.journey;if(!j?.steps?.length)return '';
  return `<div class="journey-wrap portal-tab-section" data-portal-tab="progress" hidden><div class="journey-progress-head"><strong>${j.completed}/${j.total}</strong><span>${t('milestones')}</span><small>${j.percent}%</small></div><div class="journey-progress"><span style="width:${Math.max(0,Math.min(100,j.percent))}%"></span></div><div class="journey-steps">${j.steps.map(step=>`<div class="journey-step ${step.complete?'done':''}"><span>${step.complete?'✓':step.index}</span><small>${esc(step.title)}</small></div>`).join('')}</div></div>`;
}
function assessmentCta(s){
  const j=s.journey,mission=j?.mission;if(!mission)return '';
  const band=s.placement?.bandCode,level=band==='hmena-800-1200'?'1200':['hmena-1200-1600','hmena-1600-2000','hmena-2000-2300','hmena-2300-2500'].includes(band)?'advanced':'0800';
  let action='';
  if(mission.kind==='assessment')action=`<button class="btn btn-primary start-diagnostic" data-student-id="${esc(s.id)}" data-diagnostic-level="${level}" type="button">${t('startLevelCheck')}</button>`;
  else if(mission.kind==='practice')action=`<button class="btn btn-primary journey-scroll" data-scroll-target="practice-${esc(s.id)}" type="button">${locale==='es'?'Ir a práctica':'Go to practice'}</button>`;
  else if(mission.kind==='bot')action=`<button class="btn btn-primary journey-scroll" data-scroll-target="bot-${esc(s.id)}" type="button">${locale==='es'?'Ir al reto':'Go to challenge'}</button>`;
  return `<div class="family-mission-card portal-tab-section" data-portal-tab="home"><div><span class="eyebrow">${t('todayMission')}</span><h3>${esc(mission.title)}</h3><p>${esc(mission.description)}</p>${j.activity?`<small class="mission-activity">${j.activity.correctPuzzles7d} ${locale==='es'?(j.activity.correctPuzzles7d===1?'puzzle correcto esta semana':'puzzles correctos esta semana'):(j.activity.correctPuzzles7d===1?'correct puzzle this week':'correct puzzles this week')} · ${j.activity.botGames7d} ${locale==='es'?'partidas bot':'bot games'}</small>`:''}</div>${action}</div>`;
}
function botArenaBlock(arena,studentId,placement){
  if(!arena?.bots?.length)return '';
  const hasPlacement=Boolean(placement);
  const render=b=>{const state=b.passed?t('botPassed'):!b.unlocked?t('botLocked'):(hasPlacement&&b.recommended?t('botRecommended'):'');const score=b.lastChallenge?.summary?.points;return `<article class="bot-rung ${b.passed?'passed':''} ${!b.unlocked?'locked':''}"><div><strong>${esc(b.name)}</strong><small>${t('botLevel')} ${b.targetLevel}${state?` · ${state}`:''}</small>${score!=null?`<small>${t('botPoints')}: ${score}/3</small>`:''}</div>${b.unlocked&&!b.passed?`<button class="btn btn-secondary start-bot-challenge" data-student-id="${esc(studentId)}" data-bot-code="${esc(b.code)}" type="button">${hasPlacement?t('botStart'):t('botWarmup')}</button>`:''}</article>`};
  const current=arena.bots.find(b=>b.unlocked&&!b.passed)||arena.bots.find(b=>b.recommended)||arena.bots[0];
  const rest=arena.bots.filter(b=>b.code!==current.code);
  return `${!hasPlacement?`<div class="next-lesson-box"><small>${t('startingPoint')}</small><strong>${t('botAssessmentFirst')}</strong></div>`:''}<div class="bot-ladder bot-current">${render(current)}</div>${rest.length?`<details class="compact-more"><summary>${locale==='es'?'Ver escalera completa':'View full bot ladder'}</summary><div class="bot-ladder">${rest.map(render).join('')}</div></details>`:''}`;
}

function studentCard(s){
  const rating=primaryRating(s.ratings),reviews=s.training?.reviews||[],record=recentRecord(reviews),leaks=familyLeaks(s.training),reviewed=s.training?.summary?.reviewedGames||reviews.length,puzzleCount=s.training?.activePuzzles||0;
  const ratingLabel=rating?`${rating.latestRating}`:'—',gameCount=Number(rating?.points?.[rating.points.length-1]?.gamesCount||0),ratingMeta=rating?`${humanPlatform(rating.platform)} ${rating.ratingType} · ${gameCount} ${gameCount===1?(locale==='es'?'partida':'game'):t('experience')}`:t('noRatings');
  const placement=s.placement?`${esc(s.placement.bandTitle)} · ${s.placement.ratingMin}–${s.placement.ratingMax}`:t('pending');
  const nextClass=s.upcoming?.[0];
  const assessmentDone=Boolean(s.journey?.steps?.find(x=>x.key==='assessment')?.complete),priorityLeaks=assessmentDone?leaks:[];
  const priorities=priorityLeaks.length?priorityLeaks.map((x,i)=>`<article class="focus-card"><span>${i+1}</span><div><strong>${esc(x.label)}</strong><small>${locale==='es'?`Visto ${x.occurrences}× con evidencia instructiva`:`Seen ${x.occurrences}× with instructional evidence`}</small></div></article>`).join(''):`<div class="empty">${!assessmentDone?(locale==='es'?'Completa la evaluación para fijar prioridades. Los patrones de Bullet siguen disponibles en Entrenar.':'Complete the level check to set training priorities. Bullet patterns are still available under Train.'):t('noPriorities')}</div>`;
  const puzzles=s.training?.puzzles?.filter(p=>p.status==='active').slice(0,1).map(p=>puzzleBoard(p,s.id)).join('')||`<div class="empty">${t('noPuzzles')}</div>`;
  const assignments=s.assignments?.map(x=>`<li><strong>${esc(x.title)}</strong>${x.dueAt?` · ${formatClassTime(x.dueAt)}`:''}</li>`).join('')||`<li>${t('noAssignments')}</li>`;
  const notes=s.sharedCoachNotes?.map(x=>`<li>${esc(x.note)}</li>`).join('')||'';
  const nextPlan=s.nextPlan?`<div class="next-focus-card status-ok"><small>${t('nextPlan')}</small><strong>${esc(s.nextPlan.lesson?.title||s.nextPlan.skill?.title||'—')}</strong>${s.nextPlan.lesson?.objective?`<p>${esc(s.nextPlan.lesson.objective)}</p>`:''}</div>`:`<div class="next-focus-card"><small>${t('nextPlan')}</small><strong>${t('nextPlanEmpty')}</strong></div>`;
  return `<article class="panel student-progress-card family-dashboard">
    <section class="family-hero portal-tab-section" data-portal-tab="home"><div><span class="eyebrow">${t('journey')}</span><h2>${esc(s.displayName)}</h2><p>${placement}</p></div><div class="rating-spotlight"><small>${rating?.ratingType?esc(rating.ratingType.toUpperCase()):t('ratings')}</small><strong>${ratingLabel}</strong><span>${esc(ratingMeta)}</span></div></section>
    ${milestoneStrip(s)}
    ${assessmentCta(s)}
    <section class="family-section portal-tab-section" data-portal-tab="home"><div class="family-section-head"><div><span>${t('currentSnapshot')}</span><h3>${t('recentRecord')}</h3></div></div><div class="family-metrics"><article><strong>${reviewed}</strong><span>${t('gamesReviewed')}</span></article><article><strong>${puzzleCount}</strong><span>${t('personalPuzzles')}</span></article><article><strong>${record.text}</strong><span>${locale==='es'?`Últimas ${record.total} partidas analizadas`:`Last ${record.total} analyzed games`}</span></article><article><strong>${nextClass?formatClassTime(nextClass.startsAt):'—'}</strong><span>${t('nextClass')}</span></article></div></section>
    <section class="family-section portal-tab-section" data-portal-tab="home"><div class="family-section-head"><div><span>${t('workOn')}</span><h3>${priorityLeaks.length?(locale==='es'?`${priorityLeaks.length} prioridades de entrenamiento`:`${priorityLeaks.length} training priorities`):(locale==='es'?'Prioridades de entrenamiento':'Training priorities')}</h3></div></div><div class="focus-grid">${priorities}</div></section>
    <section class="family-section practice-lab portal-tab-section" data-portal-tab="train" hidden id="practice-${esc(s.id)}"><div class="family-section-head"><div><span>${t('practiceLab')}</span><h3>${t('practiceIntro')}</h3></div></div>${practiceBankBlock(s)}<details class="compact-more training-more"><summary>${t('bonusPractice')}</summary><small class="training-disclaimer">${t('trackingNote')}</small><div class="practice-grid">${practiceMissionCards(s)}</div></details><details class="compact-more training-more"><summary>${t('fromMyGames')} · ${puzzleCount}</summary><div class="puzzle-grid">${puzzles}</div></details></section>
    <section class="family-section portal-tab-section" data-portal-tab="play" hidden id="bot-${esc(s.id)}"><div class="family-section-head"><div><span>${t('botArena')}</span><h3>${t('botHelp')}</h3></div></div>${botArenaBlock(s.botArena,s.id,s.placement)}</section>
    <section class="family-section portal-tab-section" data-portal-tab="home">${nextPlan}</section>
    <details class="family-details portal-tab-section" data-portal-tab="progress" hidden><summary>${t('allRatings')}</summary><div class="rating-grid">${ratingCards(s.ratings)}</div></details>
    <details class="family-details portal-tab-section" data-portal-tab="progress" hidden><summary>${t('openingsTitle')}</summary>${openingTrainerBlock(s.openingTrainer)}</details>
    <details class="family-details portal-tab-section" data-portal-tab="progress" hidden><summary>${t('reports')}</summary><div class="report-grid">${reportCards(s.progressReports||[])}</div></details>
    <details class="family-details portal-tab-section" data-portal-tab="progress" hidden><summary>${t('classes')} & ${t('assignments')}</summary><h4>${t('classes')}</h4><ul>${s.upcoming?.map(x=>`<li>${formatClassTime(x.startsAt)} · ${esc(x.schoolName||x.programName)} · ${t(x.instructionLocale||'en')}</li>`).join('')||`<li>${t('noClasses')}</li>`}</ul><h4>${t('assignments')}</h4><ul>${assignments}</ul>${notes?`<h4>${t('notes')}</h4><ul>${notes}</ul>`:''}</details>
    <nav class="portal-bottom-nav" aria-label="Portal navigation"><button class="portal-nav-button active" data-tab="home" type="button">⌂<span>${t('homeTab')}</span></button><button class="portal-nav-button" data-tab="train" type="button">♞<span>${t('trainTab')}</span></button><button class="portal-nav-button" data-tab="play" type="button">♜<span>${t('playTab')}</span></button><button class="portal-nav-button" data-tab="progress" type="button">↗<span>${t('progressTab')}</span></button></nav>
  </article>`;
}

let activeDiagnosticId=null;
let activeDiagnosticLevel='0800';
let activeDiagnosticStudentId=null;
function renderDiagnostic(state){
  $('#diagnostic-title').textContent=activeDiagnosticLevel==='advanced'?t('diagnosticAdvanced'):activeDiagnosticLevel==='1200'?t('diagnostic1200'):t('diagnostic');$('#diagnostic-close').textContent=t('close');
  if(state.status==='completed'){
    const sum=state.summary||{};const gaps=(sum.gaps||[]).map(g=>`<li><strong>${esc(g.title||g.code)}</strong></li>`).join('')||`<li>${t('noGaps')}</li>`;
    if(activeDiagnosticLevel==='advanced'){const sc=sum.score||{},status=sum.passed?(locale==='es'?'Banda superada':'Band cleared'):(locale==='es'?'Reforzar esta banda':'Reinforce this band'),continueNext=sum.passed&&sum.nextBand?`<button class="btn btn-primary continue-level-check" type="button">${t('continueLevelCheck')}</button>`:'';$('#diagnostic-body').innerHTML=`<div class="diagnostic-result"><span class="eyebrow">${t('diagnosticDone')}</span><h2>${t('placementResult')}: ${esc(placementLabel(state.placementBandCode))}</h2><div class="profile-stats"><article><strong>${sc.correct??0}/${sc.total??7}</strong><span>${t('score')}</span></article><article><strong>${sc.percent??0}%</strong><span>${status}</span></article></div><h3>${t('gaps')}</h3><ul>${gaps}</ul>${continueNext}</div>`;return;}
    if(activeDiagnosticLevel==='1200'){const pct=sum.competitiveFundamentals?.percent??0,continueNext=sum.cleared1200?`<button class="btn btn-primary continue-level-check" type="button">${t('continueLevelCheck')}</button>`:'';$('#diagnostic-body').innerHTML=`<div class="diagnostic-result"><span class="eyebrow">${t('diagnosticDone')}</span><h2>${t('placementResult')}: ${esc(placementLabel(state.placementBandCode))}</h2><div class="profile-stats"><article><strong>${pct}%</strong><span>${t('competitiveFundamentals')}</span></article><article><strong>${sum.cleared1200?'1200+':'800–1200'}</strong><span>${sum.cleared1200?t('ready1200'):t('score')}</span></article></div><h3>${t('gaps')}</h3><ul>${gaps}</ul>${continueNext}</div>`;return;}
    const foundationValue=sum.foundations?.skipped?'—':`${sum.foundations?.percent??0}%`;
    const seedNote=activeDiagnosticLevel==='0800'&&state.entryBasis==='rating_seed'?`<div class="next-lesson-box"><strong>${t('higherCheckpoint')}</strong></div>`:'';
    const checkNote=sum.foundationCheckRecommended?`<div class="next-lesson-box status-warn"><strong>${t('foundationCheck')}</strong></div>`:'';
    const continueNext=activeDiagnosticLevel==='0800'&&sum.cleared0800?`<button class="btn btn-primary continue-level-check" type="button">${t('continueLevelCheck')}</button>`:'';
    $('#diagnostic-body').innerHTML=`<div class="diagnostic-result"><span class="eyebrow">${t('diagnosticDone')}</span><h2>${t('placementResult')}: ${esc(placementLabel(state.placementBandCode))}</h2>${seedNote}<div class="profile-stats"><article><strong>${foundationValue}</strong><span>${t('foundations')}</span></article><article><strong>${sum.development?.total?sum.development.percent+'%':'—'}</strong><span>${t('development')}</span></article><article><strong>${sum.cleared0800?'800+':'—'}</strong><span>${sum.cleared0800?t('ready800'):t('score')}</span></article></div>${checkNote}<h3>${t('gaps')}</h3><ul>${gaps}</ul>${continueNext}</div>`;
    return;
  }
  const q=state.item;if(!q){$('#diagnostic-body').innerHTML='<div class="empty">—</div>';return;}
  const stageLabel=activeDiagnosticLevel==='advanced'?placementLabel('hmena-'+state.band):activeDiagnosticLevel==='1200'?t('competitiveFundamentals'):(q.isAnchor?(locale==='es'?'Chequeo esencial':'Anchor check'):(q.stage==='foundations'?t('foundations'):t('development')));
  const options=diagnosticOptionOrder(q).map(({option,value})=>`<label class="diagnostic-option"><input type="radio" name="diagnostic-answer" value="${value}"><span>${esc(option)}</span></label>`).join('');
  const seedNote=activeDiagnosticLevel==='0800'&&state.entryBasis==='rating_seed'?`<div class="next-lesson-box"><strong>${t('higherCheckpoint')}</strong></div>`:'';
  $('#diagnostic-body').innerHTML=`${seedNote}<div class="diagnostic-progress"><span>${stageLabel}</span><strong>${q.isAnchor?'':`${t('question')} ${q.sequence}`}</strong></div>${diagnosticBoard(q.fen)}<h2 class="diagnostic-prompt">${esc(q.prompt)}</h2><form id="diagnostic-form" data-item-id="${esc(q.id)}">${options}<button class="btn btn-primary" type="submit">${t('answer')}</button></form>`;
}
async function openDiagnostic(studentId,level='0800'){
  activeDiagnosticStudentId=studentId;activeDiagnosticLevel=level;const base=level==='advanced'?'diagnostic-advanced':level==='1200'?'diagnostic-1200':'diagnostic';
  const start=await api(`../api/portal/students/${encodeURIComponent(studentId)}/${base}/start`,{method:'POST',body:JSON.stringify({locale})});activeDiagnosticId=start.attemptId;
  const state=await api(`../api/portal/${base}/${encodeURIComponent(activeDiagnosticId)}?locale=${encodeURIComponent(locale)}`);renderDiagnostic(state);if(!$('#diagnostic-dialog').open)$('#diagnostic-dialog').showModal();
}
async function submitDiagnostic(form){
  const answer=form.querySelector('input[name="diagnostic-answer"]:checked')?.value;if(!answer)return;
  form.querySelectorAll('input,button').forEach(el=>el.disabled=true);
  const base=activeDiagnosticLevel==='advanced'?'diagnostic-advanced':activeDiagnosticLevel==='1200'?'diagnostic-1200':'diagnostic';const result=await api(`../api/portal/${base}/${encodeURIComponent(activeDiagnosticId)}/answer`,{method:'POST',body:JSON.stringify({itemId:form.dataset.itemId,answerKey:answer,locale})});
  form.insertAdjacentHTML('beforeend',`<div class="diagnostic-answer-feedback" role="status">✓ ${t('answerSaved')}</div>`);await new Promise(r=>setTimeout(r,320));
  if(result.completed){const state=await api(`../api/portal/${base}/${encodeURIComponent(activeDiagnosticId)}?locale=${encodeURIComponent(locale)}`);renderDiagnostic(state);await loadPortal();return;}
  renderDiagnostic(result.state);
}

let activeBotStudentId=null,activeBotChallengeId=null,activeBotGameId=null;
function botGameBoard(game){
  const {map}=fenSquares(game.fen),white=game.studentColor==='white',files=white?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'],ranks=white?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];
  const squares=[];for(const rank of ranks)for(const file of files){const sq=file+rank,piece=map.get(sq)||'',fi=file.charCodeAt(0)-97,light=(fi+rank)%2===1;squares.push(`<button type="button" class="puzzle-square bot-square ${light?'light':'dark'}" data-square="${sq}" data-piece="${piece}">${chessPieces[piece]||''}</button>`);}
  return `<div class="bot-game" data-game-id="${esc(game.id)}" data-student-color="${esc(game.studentColor)}"><div class="puzzle-board bot-board">${squares.join('')}</div><div class="bot-move-state" aria-live="polite"></div></div>`;
}
function renderBotGame(game,challenge=null){
  $('#bot-title').textContent=t('botArena');$('#bot-close').textContent=t('close');activeBotGameId=game?.id||null;
  if(game?.status==='completed'){
    const summary=challenge?.summary||{},finished=challenge&&challenge.status!=='in_progress';
    $('#bot-body').innerHTML=`<div class="next-lesson-box ${challenge?.status==='passed'?'status-ok':''}"><small>${t('botGame')} ${game.gameNo}/3</small><strong>${esc(game.result||'—')}</strong><p>${t('botPoints')}: ${summary.points??'—'}/3${summary.avgCpLoss!=null?` · Avg CPL ${summary.avgCpLoss}`:''}</p>${finished?`<p><strong>${challenge.status==='passed'?t('botPass'):t('botFail')}</strong></p><p>${t('botPractical')}: ${summary.practicalStrength??'—'}</p>`:`<button class="btn btn-primary next-bot-game" type="button">${t('botNext')}</button>`}</div>`;
    if(!$('#bot-dialog').open)$('#bot-dialog').showModal();return;
  }
  $('#bot-body').innerHTML=`<div class="diagnostic-progress"><span>${t('botGame')} ${game.gameNo}/3</span><strong>${t('yourColor')}: ${t(game.studentColor)}</strong></div>${botGameBoard(game)}<small class="puzzle-help">${t('selectMove')}</small>`;
  if(!$('#bot-dialog').open)$('#bot-dialog').showModal();
}
async function startBotGame(){const game=await api(`../api/portal/students/${encodeURIComponent(activeBotStudentId)}/bot-challenges/${encodeURIComponent(activeBotChallengeId)}/games/start`,{method:'POST'});renderBotGame(game);}
async function openBotChallenge(studentId,botCode){
  activeBotStudentId=studentId;const challenge=await api(`../api/portal/students/${encodeURIComponent(studentId)}/bot-challenges`,{method:'POST',body:JSON.stringify({botCode})});activeBotChallengeId=challenge.id;await startBotGame();
}
async function sendBotMove(card,from,to){
  const fromPiece=card.querySelector(`.bot-square[data-square="${CSS.escape(from)}"]`)?.dataset.piece||'';let moveUci=from+to;if(/[Pp]/.test(fromPiece)&&/[18]$/.test(to))moveUci+='q';
  const state=card.querySelector('.bot-move-state');state.textContent=locale==='es'?'Pensando…':'Thinking…';
  const result=await api(`../api/portal/students/${encodeURIComponent(activeBotStudentId)}/bot-games/${encodeURIComponent(activeBotGameId)}/move`,{method:'POST',body:JSON.stringify({moveUci})});
  renderBotGame(result.game,result.challenge);if(result.challenge&&result.challenge.status!=='in_progress')await loadPortal();
}

function setPortalTab(tab='home'){activePortalTab=['home','train','play','progress'].includes(tab)?tab:'home';localStorage.setItem('cis_portal_tab',activePortalTab);document.querySelectorAll('.family-dashboard').forEach(root=>{root.querySelectorAll('.portal-tab-section').forEach(el=>el.hidden=el.dataset.portalTab!==activePortalTab);root.querySelectorAll('.portal-nav-button').forEach(btn=>btn.classList.toggle('active',btn.dataset.tab===activePortalTab));});window.scrollTo({top:0,behavior:'smooth'});}

async function loadPortal(){
  const data=await api('../api/portal/me');
  if(data.locale&&data.locale!==locale){locale=data.locale;localStorage.setItem('hmena_portal_locale',locale);applyStatic();}
  $('#language-panel').hidden=true;$('#language-tools').hidden=false;$('#login-panel').hidden=true;$('#portal').hidden=false;$('#logout').hidden=false;
  $('#welcome').textContent=data.account.role==='guardian'?`${t('hello')}, ${data.account.displayName}`:t('title');
  $('#students').innerHTML=data.students.map(studentCard).join('')||`<div class="empty">${t('noStudents')}</div>`;setPortalTab(activePortalTab);
}
function chooseLanguage(nextLocale){locale=nextLocale;localStorage.setItem('hmena_portal_locale',locale);applyStatic();$('#language-panel').hidden=true;$('#language-tools').hidden=false;if(!token){$('#login-panel').hidden=false;$('#portal').hidden=true;}}
async function saveLocale(){localStorage.setItem('hmena_portal_locale',locale);applyStatic();if(token){await api('../api/portal/preferences',{method:'PATCH',body:JSON.stringify({preferredLocale:locale})});await loadPortal();}}
document.querySelectorAll('[data-locale]').forEach(button=>button.addEventListener('click',()=>chooseLanguage(button.dataset.locale)));
$('#locale-select').addEventListener('change',async event=>{locale=event.target.value;try{await saveLocale();}catch(e){$('#portal-error').textContent=e.message;}});
$('#login-form').addEventListener('submit',async event=>{event.preventDefault();$('#portal-error').textContent='';const payload=Object.fromEntries(new FormData(event.target).entries());try{const result=await api('../api/portal/login',{method:'POST',body:JSON.stringify(payload)});token=result.sessionToken;localStorage.setItem('hmena_student_session',token);if(result.account?.preferredLocale!==locale)await api('../api/portal/preferences',{method:'PATCH',body:JSON.stringify({preferredLocale:locale})});event.target.reset();await loadPortal();}catch(e){$('#portal-error').textContent=e.message;}});
document.addEventListener('click',async event=>{
  const portalNav=event.target.closest('.portal-nav-button');if(portalNav){setPortalTab(portalNav.dataset.tab);return;}
  const journeyScroll=event.target.closest('.journey-scroll');if(journeyScroll){const target=document.getElementById(journeyScroll.dataset.scrollTarget);if(target?.dataset.portalTab)setPortalTab(target.dataset.portalTab);target?.scrollIntoView({behavior:'smooth',block:'start'});return;}
  const themeOpen=event.target.closest('.open-theme-practice');if(themeOpen){try{await openThemePractice(themeOpen.dataset.studentId,themeOpen.dataset.theme);}catch(e){$('#portal-error').textContent=e.message;}return;}
  const themeSquare=event.target.closest('.theme-square');if(themeSquare){const card=themeSquare.closest('.theme-game');if(!card)return;const selected=card.dataset.selected||'',piece=themeSquare.dataset.piece||'',turn=card.dataset.turn;if(!selected){const own=piece&&(turn==='w'?piece===piece.toUpperCase():piece===piece.toLowerCase());if(!own)return;card.dataset.selected=themeSquare.dataset.square;themeSquare.classList.add('selected');return;}card.querySelectorAll('.theme-square.selected').forEach(x=>x.classList.remove('selected'));card.dataset.selected='';if(selected===themeSquare.dataset.square)return;const from=card.querySelector(`.theme-square[data-square="${CSS.escape(selected)}"]`),fromPiece=from?.dataset.piece||'';let answerMove=selected+themeSquare.dataset.square;if(/[Pp]/.test(fromPiece)&&/[18]$/.test(themeSquare.dataset.square))answerMove+='q';try{const result=await api(`../api/portal/students/${encodeURIComponent(activeThemeStudentId)}/practice-bank/${encodeURIComponent(card.dataset.puzzleId)}/attempt`,{method:'POST',body:JSON.stringify({answerMove})});const msg=card.querySelector('.theme-result');if(result.correct){msg.textContent=`${t('correctMove')}${result.rated?` · ${result.ratingDelta>=0?'+':''}${result.ratingDelta} ${t('puzzleRating')}`:''}`;setTimeout(()=>loadThemePuzzle().catch(e=>{$('#portal-error').textContent=e.message;}),450);loadPortal().catch(()=>{});}else msg.textContent=`${t('tryAgain')}${result.rated?` · ${result.ratingDelta} ${t('puzzleRating')}`:''}`;}catch(e){$('#portal-error').textContent=e.message;}return;}
  const streakStart=event.target.closest('.start-puzzle-streak');if(streakStart){try{await openPuzzleStreak(streakStart.dataset.studentId);}catch(e){$('#portal-error').textContent=e.message;}return;}
  const stormStart=event.target.closest('.start-puzzle-storm');if(stormStart){try{await openPuzzleStorm(stormStart.dataset.studentId);}catch(e){$('#portal-error').textContent=e.message;}return;}
  const stormRestart=event.target.closest('.restart-puzzle-storm');if(stormRestart){try{activeStormRunId=null;await openPuzzleStorm(activeStormStudentId);}catch(e){$('#portal-error').textContent=e.message;}return;}
  const stormSquare=event.target.closest('.storm-square');if(stormSquare){const card=stormSquare.closest('.storm-game');if(!card)return;const selected=card.dataset.selected||'',piece=stormSquare.dataset.piece||'',turn=card.dataset.turn;if(!selected){const own=piece&&(turn==='w'?piece===piece.toUpperCase():piece===piece.toLowerCase());if(!own)return;card.dataset.selected=stormSquare.dataset.square;stormSquare.classList.add('selected');return;}card.querySelectorAll('.storm-square.selected').forEach(x=>x.classList.remove('selected'));card.dataset.selected='';if(selected===stormSquare.dataset.square)return;const from=card.querySelector(`.storm-square[data-square="${CSS.escape(selected)}"]`),fromPiece=from?.dataset.piece||'';let answerMove=selected+stormSquare.dataset.square;if(/[Pp]/.test(fromPiece)&&/[18]$/.test(stormSquare.dataset.square))answerMove+='q';try{const result=await api(`../api/portal/students/${encodeURIComponent(activeStormStudentId)}/practice-storm/${encodeURIComponent(activeStormRunId)}/answer`,{method:'POST',body:JSON.stringify({answerMove})});renderStorm(result.state,result.correct?t('correctMove'):t('tryAgain'));}catch(e){if(String(e.message).includes('not active'))await finishStormFromServer();else $('#portal-error').textContent=e.message;}return;}
  const streakRestart=event.target.closest('.restart-puzzle-streak');if(streakRestart){try{activeStreakRunId=null;await openPuzzleStreak(activeStreakStudentId);}catch(e){$('#portal-error').textContent=e.message;}return;}
  const streakSquare=event.target.closest('.streak-square');if(streakSquare){const card=streakSquare.closest('.streak-game');if(!card)return;const selected=card.dataset.selected||'',piece=streakSquare.dataset.piece||'',turn=card.dataset.turn;if(!selected){const own=piece&&(turn==='w'?piece===piece.toUpperCase():piece===piece.toLowerCase());if(!own)return;card.dataset.selected=streakSquare.dataset.square;streakSquare.classList.add('selected');return;}card.querySelectorAll('.streak-square.selected').forEach(x=>x.classList.remove('selected'));card.dataset.selected='';if(selected===streakSquare.dataset.square)return;const from=card.querySelector(`.streak-square[data-square="${CSS.escape(selected)}"]`),fromPiece=from?.dataset.piece||'';let answerMove=selected+streakSquare.dataset.square;if(/[Pp]/.test(fromPiece)&&/[18]$/.test(streakSquare.dataset.square))answerMove+='q';try{const result=await api(`../api/portal/students/${encodeURIComponent(activeStreakStudentId)}/practice-streak/${encodeURIComponent(activeStreakRunId)}/answer`,{method:'POST',body:JSON.stringify({answerMove})});if(result.correct){renderStreak(result.state);}else{renderStreak(result.state);}}catch(e){$('#portal-error').textContent=e.message;}return;}

  const continueLevel=event.target.closest('.continue-level-check');if(continueLevel){if(!activeDiagnosticStudentId)return;continueLevel.disabled=true;try{await openDiagnostic(activeDiagnosticStudentId,activeDiagnosticLevel==='0800'?'1200':'advanced');}catch(e){$('#portal-error').textContent=e.message;continueLevel.disabled=false;}return;}
  const submitPractice=event.target.closest('.submit-practice');if(submitPractice){try{await api(`../api/portal/students/${encodeURIComponent(submitPractice.dataset.studentId)}/practice-missions/${encodeURIComponent(submitPractice.dataset.assignmentId)}/submit`,{method:'POST',body:JSON.stringify({})});await loadPortal();}catch(e){$('#portal-error').textContent=e.message;}return;}
  const startBot=event.target.closest('.start-bot-challenge');if(startBot){try{await openBotChallenge(startBot.dataset.studentId,startBot.dataset.botCode);}catch(e){$('#portal-error').textContent=e.message;}return;}
  const nextBot=event.target.closest('.next-bot-game');if(nextBot){try{await startBotGame();}catch(e){$('#portal-error').textContent=e.message;}return;}
  const botSquare=event.target.closest('.bot-square');if(botSquare){const card=botSquare.closest('.bot-game');if(!card)return;const color=card.dataset.studentColor,selected=card.dataset.selected||'',piece=botSquare.dataset.piece||'';if(!selected){const own=piece&&(color==='white'?piece===piece.toUpperCase():piece===piece.toLowerCase());if(!own)return;card.dataset.selected=botSquare.dataset.square;botSquare.classList.add('selected');return;}card.querySelectorAll('.bot-square.selected').forEach(x=>x.classList.remove('selected'));card.dataset.selected='';if(selected===botSquare.dataset.square)return;try{await sendBotMove(card,selected,botSquare.dataset.square);}catch(e){card.querySelector('.bot-move-state').textContent=e.message;}return;}
  const bankSquare=event.target.closest('.bank-square');if(bankSquare){
    const card=bankSquare.closest('.bank-puzzle');if(!card||card.classList.contains('solved'))return;
    const selected=card.dataset.selected||'',piece=bankSquare.dataset.piece||'',turn=card.dataset.turn;
    if(!selected){const own=piece&&(turn==='w'?piece===piece.toUpperCase():piece===piece.toLowerCase());if(!own)return;card.dataset.selected=bankSquare.dataset.square;bankSquare.classList.add('selected');return;}
    card.querySelectorAll('.bank-square.selected').forEach(x=>x.classList.remove('selected'));card.dataset.selected='';if(selected===bankSquare.dataset.square)return;
    const from=card.querySelector(`.bank-square[data-square="${CSS.escape(selected)}"]`),fromPiece=from?.dataset.piece||'';let answerMove=selected+bankSquare.dataset.square;if(/[Pp]/.test(fromPiece)&&/[18]$/.test(bankSquare.dataset.square))answerMove+='q';
    try{const result=await api(`../api/portal/students/${encodeURIComponent(card.dataset.studentId)}/practice-bank/${encodeURIComponent(card.dataset.puzzleId)}/attempt`,{method:'POST',body:JSON.stringify({answerMove})});const msg=card.querySelector('.puzzle-result');if(result.correct){msg.textContent=`${t('correctMove')}${result.rated?` · ${result.ratingDelta>=0?'+':''}${result.ratingDelta} ${t('puzzleRating')}`:''}`;card.classList.add('solved');setTimeout(()=>loadPortal().catch(()=>{}),650);}else msg.textContent=`${t('tryAgain')}${result.rated?` · ${result.ratingDelta} ${t('puzzleRating')}`:''}`;}catch(e){$('#portal-error').textContent=e.message;}return;
  }
  const square=event.target.closest('.puzzle-square');
  if(square){
    const card=square.closest('.mistake-puzzle');if(!card||card.classList.contains('solved'))return;
    const selected=card.dataset.selected||'',piece=square.dataset.piece||'',turn=card.dataset.turn;
    if(!selected){const own=piece&&(turn==='w'?piece===piece.toUpperCase():piece===piece.toLowerCase());if(!own)return;card.dataset.selected=square.dataset.square;square.classList.add('selected');return;}
    card.querySelectorAll('.puzzle-square.selected').forEach(x=>x.classList.remove('selected'));card.dataset.selected='';
    if(selected===square.dataset.square)return;
    const from=card.querySelector(`.puzzle-square[data-square="${CSS.escape(selected)}"]`),fromPiece=from?.dataset.piece||'';
    let answerMove=selected+square.dataset.square;if(/[Pp]/.test(fromPiece)&&/[18]$/.test(square.dataset.square))answerMove+='q';
    try{const result=await api(`../api/portal/students/${encodeURIComponent(card.dataset.studentId)}/puzzles/${encodeURIComponent(card.dataset.puzzleId)}/attempt`,{method:'POST',body:JSON.stringify({answerMove})});const msg=card.querySelector('.puzzle-result');if(result.correct){msg.textContent=t('correctMove');card.classList.add('solved');setTimeout(()=>loadPortal().catch(()=>{}),700);}else msg.textContent=t('tryAgain');}catch(e){$('#portal-error').textContent=e.message;}return;
  }
  const button=event.target.closest('.start-diagnostic');if(!button)return;try{await openDiagnostic(button.dataset.studentId,button.dataset.diagnosticLevel||'0800');}catch(e){$('#portal-error').textContent=e.message;}
});
document.addEventListener('submit',async event=>{if(event.target.id!=='diagnostic-form')return;event.preventDefault();try{await submitDiagnostic(event.target);}catch(e){$('#portal-error').textContent=e.message;}});
$('#storm-dialog').addEventListener('close',()=>{if(stormTimer){clearInterval(stormTimer);stormTimer=null;}});
$('#logout').onclick=()=>{token='';localStorage.removeItem('hmena_student_session');location.reload();};
if(token){loadPortal().catch(()=>{localStorage.removeItem('hmena_student_session');token='';if(locale)chooseLanguage(locale);});}
else if(locale){chooseLanguage(locale);}
else{$('#language-panel').hidden=false;$('#login-panel').hidden=true;$('#language-tools').hidden=true;}
