const BASE='https://lichess.org';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const providerError=async response=>{const error=new Error(`Lichess ${response.status}: ${await response.text()}`);error.status=response.status;return error;};
export class LichessClient{
 constructor({fetchImpl=fetch}={}){this.fetch=fetchImpl;this.queue=Promise.resolve();}
 async request(path,options={}){const task=async()=>{let response=await this.fetch(`${BASE}${path}`,options);if(response.status===429){await sleep(60000);response=await this.fetch(`${BASE}${path}`,options);}if(!response.ok)throw await providerError(response);return response;};const next=this.queue.then(task,task);this.queue=next.then(()=>undefined,()=>undefined);return next;}
 async getUser(username){const response=await this.request(`/api/user/${encodeURIComponent(username)}`,{headers:{Accept:'application/json'}});return response.json();}
 async getGames(username,{since,until,max=50}={}){const qs=new URLSearchParams({max:String(max),moves:'false',clocks:'false',evals:'false',opening:'false'});if(since)qs.set('since',String(since));if(until)qs.set('until',String(until));const response=await this.request(`/api/games/user/${encodeURIComponent(username)}?${qs}`,{headers:{Accept:'application/x-ndjson'}});const text=await response.text();return text.split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line));}
 async createChallenge(username,token,{rated=false,clockLimit=600,clockIncrement=5,color='random',variant='standard',acceptByToken}={}){if(!token)throw new Error('A Lichess OAuth token with challenge permission is required');const body=new URLSearchParams({rated:String(rated),'clock.limit':String(clockLimit),'clock.increment':String(clockIncrement),color,variant});if(acceptByToken)body.set('acceptByToken',acceptByToken);const response=await this.request(`/api/challenge/${encodeURIComponent(username)}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body});return response.json();}
}
export function lichessRating(profile,preferred=['rapid','blitz','bullet','classical']){for(const key of preferred){const rating=profile?.perfs?.[key]?.rating;if(Number.isFinite(rating))return{type:key,rating};}return{type:null,rating:null};}
