import {seedHmenaFramework,HMENA_FRAMEWORK_ID} from './hmena-curriculum.js';

const F='hmena-0-400',D='hmena-400-800';
const foundations=[
  {n:1,skills:['FND-BOARD','FND-PIECES'],en:['Board Coordinates & Piece Movement','Set up the board, name squares, and move every piece legally.',['Board orientation and coordinates','Piece movement and captures','Knight jumping vs sliding pieces'],'Coordinate hunt + legal-move relay','Practice naming 12 squares and demonstrate each piece move','Name e4, a1, h8 and show one legal move for every piece.'],es:['Coordenadas del tablero y movimiento de piezas','Colocar el tablero, nombrar casillas y mover cada pieza legalmente.',['Orientación y coordenadas','Movimiento y capturas','El caballo salta; las piezas deslizantes no'],'Búsqueda de coordenadas + relevo de jugadas legales','Practicar 12 casillas y demostrar el movimiento de cada pieza','Nombra e4, a1, h8 y muestra una jugada legal de cada pieza.']},
  {n:2,skills:['FND-PAWNS','FND-LEGAL'],en:['Pawns, Legal Moves & King Safety','Use pawn rules correctly and reject moves that expose the king.',['Pawn movement, capture and promotion','Illegal king exposure','Attacked squares'],'Pawn race + legal/illegal sorting','Five pawn-rule mini positions','Explain why a move that leaves your king in check is illegal.'],es:['Peones, jugadas legales y seguridad del rey','Usar correctamente las reglas del peón y rechazar jugadas que expongan al rey.',['Movimiento, captura y promoción del peón','Exposición ilegal del rey','Casillas atacadas'],'Carrera de peones + clasificación legal/ilegal','Cinco mini posiciones de reglas del peón','Explica por qué es ilegal dejar a tu rey en jaque.']},
  {n:3,skills:['FND-CHECK','FND-CBR'],en:['Check & CBR','Recognize check and escape using Capture, Block, or Run.',['Identify the checking piece','Capture the checker','Block when possible','Move the king safely'],'CBR stations with short positions','Solve 8 check-response positions','Name all legal CBR responses in one position.'],es:['Jaque y CBR','Reconocer el jaque y escapar con Capturar, Bloquear o Retirar el rey.',['Identificar la pieza que da jaque','Capturar al atacante','Bloquear cuando sea posible','Mover el rey con seguridad'],'Estaciones CBR con posiciones cortas','Resolver 8 posiciones de respuesta al jaque','Nombra todas las respuestas CBR legales en una posición.']},  {n:4,skills:['FND-MATE1'],en:['Checkmate & Mate in One','Distinguish check from checkmate and find basic mate-in-one patterns.',['Check vs checkmate','Escape-square scan','Protected checking pieces'],'Mate-or-not game + mate-in-one race','10 mate-in-one puzzles','Explain why the king has no legal escape.'],es:['Jaque mate y mate en una','Distinguir jaque de jaque mate y encontrar mates básicos en una.',['Jaque vs jaque mate','Revisión de casillas de escape','Piezas que protegen al atacante'],'Juego mate-o-no + carrera de mate en una','10 problemas de mate en una','Explica por qué el rey no tiene escape legal.']},
  {n:5,skills:['FND-THINK'],en:['Think Before You Move','Build a repeatable safety check before every move.',['What is my opponent threatening?','What is hanging?','What changed after the last move?'],'Blunder detective with mini positions','Use the safety checklist in 3 short games','Say the checklist before choosing a move.'],es:['Piensa antes de mover','Construir una revisión de seguridad repetible antes de cada jugada.',['¿Qué amenaza mi rival?','¿Qué pieza está colgada?','¿Qué cambió tras la última jugada?'],'Detective de errores con mini posiciones','Usar la lista de seguridad en 3 partidas cortas','Di la lista antes de elegir una jugada.']},
  {n:6,skills:['FND-OPENING'],en:['Opening Habits: Center, Develop, Castle','Play the opening with healthy priorities instead of memorizing moves.',['Control the center','Develop minor pieces','Castle early','Avoid repeated queen moves'],'Opening move sorting + mini games','Play two games using the opening checklist','List the three opening priorities in order.'],es:['Hábitos de apertura: centro, desarrollo y enroque','Jugar la apertura con buenas prioridades sin memorizar jugadas.',['Controlar el centro','Desarrollar piezas menores','Enrocar temprano','Evitar mover la dama repetidamente'],'Clasificar jugadas de apertura + mini partidas','Jugar dos partidas usando la lista de apertura','Enumera las tres prioridades de apertura.']},
  {n:7,skills:['FND-TRAPS'],en:["Scholar's Mate & Fool's Mate",'Recognize beginner mating traps and defend without panic.',['f7/f2 weakness','Scholar’s Mate pattern','Fool’s Mate pattern','Safe defensive development'],'Trap recognition cards + defense rehearsal','Identify trap or normal development in 8 examples','Show one safe defense against Scholar’s Mate.'],es:['Mate del Pastor y Mate del Loco','Reconocer trampas básicas de mate y defender sin entrar en pánico.',['Debilidad f7/f2','Patrón del Mate del Pastor','Patrón del Mate del Loco','Desarrollo defensivo seguro'],'Tarjetas de reconocimiento + ensayo defensivo','Identificar trampa o desarrollo normal en 8 ejemplos','Muestra una defensa segura contra el Mate del Pastor.']},  {n:8,skills:['FND-QK-MATE'],en:['Queen vs King Checkmate','Convert queen versus lone king without stalemating.',['Restrict the king','Bring your king closer','Keep safe queen distance','Avoid stalemate'],'Coach-guided box method + timed conversion','Complete Q vs K twice from different starts','Deliver mate without stalemate.'],es:['Jaque mate de dama contra rey','Convertir dama contra rey solo sin provocar ahogado.',['Restringir al rey','Acercar tu rey','Mantener distancia segura con la dama','Evitar el ahogado'],'Método de caja guiado + conversión con tiempo','Completar dama vs rey dos veces desde posiciones distintas','Da mate sin provocar ahogado.']},
  {n:9,skills:['FND-LEGAL','FND-THINK','FND-OPENING'],review:true,en:['Complete Beginner Game','Connect rules, safe thinking, and opening habits in a full game.',['Legal-move discipline','Safety checklist','Healthy opening priorities','Finish the game correctly'],'Guided full game with pause-and-explain moments','Play one annotated practice game','Explain one good decision and one mistake from the game.'],es:['Partida completa de principiante','Conectar reglas, pensamiento seguro y hábitos de apertura en una partida completa.',['Disciplina de jugadas legales','Lista de seguridad','Buenas prioridades de apertura','Terminar correctamente la partida'],'Partida completa guiada con pausas para explicar','Jugar una partida de práctica anotada','Explica una buena decisión y un error de la partida.']},
  {n:10,skills:['FND-BOARD','FND-PIECES','FND-PAWNS','FND-LEGAL','FND-CHECK','FND-CBR','FND-MATE1','FND-OPENING','FND-TRAPS','FND-QK-MATE','FND-THINK'],review:true,en:['Foundations Challenge & Assessment','Demonstrate the core 0–400 skills in one structured session.',['Rules and coordinates','Check/checkmate','Opening habits','Queen vs king','Thinking routine'],'Skill stations + short game + mini assessment','Review any skills marked for reinforcement','Pass the Foundations exit criteria or receive a targeted review plan.'],es:['Reto y evaluación de Fundamentos','Demostrar las habilidades principales de 0–400 en una sesión estructurada.',['Reglas y coordenadas','Jaque/jaque mate','Hábitos de apertura','Dama contra rey','Rutina de pensamiento'],'Estaciones de habilidades + partida corta + mini evaluación','Repasar habilidades marcadas para reforzar','Cumple los criterios de salida de Fundamentos o recibe un plan de refuerzo.']}
];
const development=[
  {n:1,skills:['DEV-HANGING','DEV-MATERIAL'],en:['Hanging Pieces & Material','Stop one-move blunders and judge basic trades with piece values.',['Loose-piece scan','Attackers vs defenders','Piece values','Fair and unfair trades'],'Capture-or-protect stations','Find the hanging piece in 10 positions','Explain whether a proposed trade wins, loses, or keeps material.'],es:['Piezas colgadas y material','Evitar errores de una jugada y evaluar cambios básicos con valores de piezas.',['Revisión de piezas sueltas','Atacantes vs defensores','Valores de piezas','Cambios favorables y desfavorables'],'Estaciones capturar-o-proteger','Encuentra la pieza colgada en 10 posiciones','Explica si un cambio propuesto gana, pierde o mantiene material.']},
  {n:2,skills:['DEV-THREATS','DEV-CCT'],en:['Threats & CCT Scan','Recognize immediate threats and generate forcing candidates with Checks, Captures, Threats.',['Opponent threat first','Checks','Captures','Threats','Candidate ordering'],'CCT race in short positions','Use CCT in 8 tactical positions','Name your opponent’s threat and your top two candidates.'],es:['Amenazas y revisión CCT','Reconocer amenazas inmediatas y generar candidatas forzantes con Jaques, Capturas y Amenazas.',['Primero la amenaza rival','Jaques','Capturas','Amenazas','Orden de candidatas'],'Carrera CCT en posiciones cortas','Usar CCT en 8 posiciones tácticas','Nombra la amenaza rival y tus dos mejores candidatas.']},
  {n:3,skills:['DEV-FORK'],en:['Forks & Double Attacks','Create and detect forks with knights, pawns, and major pieces.',['Two targets at once','Knight-fork geometry','King-plus-piece forks','Defending a fork'],'Fork finder + create-your-own fork','Solve 12 fork positions','Show why both targets cannot be saved.'],es:['Tenedores y ataques dobles','Crear y detectar tenedores con caballos, peones y piezas mayores.',['Dos objetivos a la vez','Geometría del tenedor de caballo','Tenedores al rey y otra pieza','Defender un tenedor'],'Buscador de tenedores + crea tu propio tenedor','Resolver 12 posiciones de tenedor','Muestra por qué no se pueden salvar ambos objetivos.']},  {n:4,skills:['DEV-PIN'],en:['Pins','Recognize absolute and relative pins and exploit pinned pieces safely.',['Absolute vs relative pin','Pin to king vs valuable piece','Attacking the pinned piece','Breaking a pin'],'Pin-or-not sorting + winning the pinned piece','Solve 10 pin positions','Identify the pinned piece and explain whether it can legally move.'],es:['Clavadas','Reconocer clavadas absolutas y relativas y aprovechar piezas clavadas con seguridad.',['Clavada absoluta vs relativa','Clavada al rey vs pieza valiosa','Atacar la pieza clavada','Romper una clavada'],'Clasificar clavada-o-no + ganar la pieza clavada','Resolver 10 posiciones de clavada','Identifica la pieza clavada y explica si puede moverse legalmente.']},
  {n:5,skills:['DEV-SKEWER'],en:['Skewers','Use line pieces to attack a valuable piece and win what is behind it.',['Front target vs rear target','Files, ranks, diagonals','Forcing the valuable piece away','Avoiding fake skewers'],'Skewer spotting on files and diagonals','Solve 10 skewer positions','Name the front target and the piece behind it.'],es:['Enfiladas','Usar piezas de línea para atacar una pieza valiosa y ganar lo que está detrás.',['Objetivo frontal y objetivo posterior','Columnas, filas y diagonales','Forzar que se aparte la pieza valiosa','Evitar falsas enfiladas'],'Detectar enfiladas en columnas y diagonales','Resolver 10 posiciones de enfilada','Nombra el objetivo frontal y la pieza que está detrás.']},
  {n:6,skills:['DEV-DISCOVERED'],en:['Discovered Attack & Discovered Check','Move one piece to reveal a second attack and calculate the forcing result.',['Moving piece vs revealed attacker','Discovered attack','Discovered check','Double-threat potential'],'Reveal-the-line puzzles','Solve 10 discovered-attack positions','Explain which piece moves and which piece gives the revealed attack.'],es:['Ataque descubierto y jaque descubierto','Mover una pieza para descubrir un segundo ataque y calcular el resultado forzante.',['Pieza que se mueve vs atacante revelado','Ataque descubierto','Jaque descubierto','Potencial de doble amenaza'],'Problemas de descubrir la línea','Resolver 10 posiciones de ataque descubierto','Explica qué pieza se mueve y cuál realiza el ataque revelado.']},  {n:7,skills:['DEV-BACKRANK'],en:['Back-Rank Mate & Escape Squares','Recognize back-rank danger and create luft before it becomes tactical.',['King trapped by pawns','Rook/queen invasion','Luft','Back-rank defense'],'Back-rank pattern cards + prevention drill','Solve 8 attack/defense positions','Show one move that removes back-rank danger.'],es:['Mate en la última fila y casillas de escape','Reconocer el peligro de última fila y crear aire antes de que sea táctico.',['Rey atrapado por peones','Invasión de torre/dama','Aire para el rey','Defensa de última fila'],'Tarjetas de patrones + ejercicio de prevención','Resolver 8 posiciones de ataque/defensa','Muestra una jugada que elimine el peligro de última fila.']},
  {n:8,skills:['DEV-LADDER'],en:['Ladder Mate & Rook Mate','Convert basic major-piece mates efficiently and safely.',['Cut off the king','Shrink the box','Coordinate with your king','Avoid stalemate and hanging the rook'],'Timed mate technique from multiple starts','Complete rook/ladder mate twice','Finish the mate with correct king support.'],es:['Mate escalera y mate con torre','Convertir mates básicos con piezas mayores de forma eficiente y segura.',['Cortar al rey','Reducir la caja','Coordinar con tu rey','Evitar ahogado y perder la torre'],'Técnica de mate con tiempo desde distintas posiciones','Completar mate con torre/escalera dos veces','Finaliza el mate con apoyo correcto del rey.']},
  {n:9,skills:['DEV-KP-END'],en:['King + Pawn vs King','Use king support and opposition to judge basic pawn endings.',['King in front of pawn','Opposition','Key squares','Win vs draw recognition'],'Play both sides of K+P vs K','Classify 8 positions as win/draw','Explain whether the pawn promotes and why.'],es:['Rey y peón contra rey','Usar apoyo del rey y oposición para evaluar finales básicos de peones.',['Rey delante del peón','Oposición','Casillas clave','Reconocer victoria vs tablas'],'Jugar ambos lados de R+P vs R','Clasificar 8 posiciones como victoria/tablas','Explica si el peón corona y por qué.']},
  {n:10,skills:['DEV-HANGING','DEV-MATERIAL','DEV-THREATS','DEV-FORK','DEV-PIN','DEV-SKEWER','DEV-DISCOVERED','DEV-BACKRANK','DEV-LADDER','DEV-KP-END','DEV-CCT'],review:true,en:['Development Challenge & Assessment','Demonstrate the core 400–800 tactical, thinking, and endgame skills.',['Blunder prevention','CCT calculation','Core tactics','Back-rank safety','Basic endgames'],'Mixed skill stations + short rated-style game','Review the two weakest skills from the assessment','Pass Development criteria or receive a targeted reinforcement plan.'],es:['Reto y evaluación de Desarrollo','Demostrar las habilidades principales de táctica, pensamiento y finales de 400–800.',['Prevención de errores','Cálculo CCT','Tácticas fundamentales','Seguridad de última fila','Finales básicos'],'Estaciones mixtas + partida corta estilo competitivo','Repasar las dos habilidades más débiles de la evaluación','Cumple los criterios de Desarrollo o recibe un plan de refuerzo dirigido.']}
];
const all=[...foundations.map(x=>({...x,band:F})),...development.map(x=>({...x,band:D}))];
const lessonId=row=>`LESSON-HMENA-${row.band===F?'0400':'0800'}-L${String(row.n).padStart(2,'0')}`;
const skillId=(db,code)=>db.prepare(`SELECT s.id FROM curriculum_skills s JOIN curriculum_tracks t ON t.id=s.track_id WHERE s.code=? AND t.framework_id=?`).get(code,HMENA_FRAMEWORK_ID)?.id;
const localizedContent=lang=>({keyPoints:lang[2],activity:lang[3],homework:lang[4],exitTicket:lang[5]});

export function seedHmenaCourse0800(db){
  seedHmenaFramework(db);
  const insertLesson=db.prepare(`INSERT INTO lessons(id,skill_id,title,objective,duration_minutes,difficulty,content_json,active) VALUES (?,?,?,?,60,?,?,1) ON CONFLICT(id) DO UPDATE SET skill_id=excluded.skill_id,title=excluded.title,objective=excluded.objective,difficulty=excluded.difficulty,content_json=excluded.content_json,active=1`);
  const link=db.prepare(`INSERT INTO lesson_skills(lesson_id,skill_id,role,sequence_no) VALUES (?,?,?,?) ON CONFLICT(lesson_id,skill_id) DO UPDATE SET role=excluded.role,sequence_no=excluded.sequence_no`);
  const loc=db.prepare(`INSERT INTO curriculum_localizations(entity_type,entity_id,locale,title,objective,content_json) VALUES ('lesson',?,?,?,?,?) ON CONFLICT(entity_type,entity_id,locale) DO UPDATE SET title=excluded.title,objective=excluded.objective,content_json=excluded.content_json,updated_at=CURRENT_TIMESTAMP`);
  db.transaction(()=>{for(const row of all){const lid=lessonId(row),primary=skillId(db,row.skills[0]);if(!primary)throw new Error(`missing skill ${row.skills[0]}`);insertLesson.run(lid,primary,row.en[0],row.en[1],row.band,JSON.stringify({framework:'HMENA 0–2500',bandCode:row.band,lessonNumber:row.n,skillCodes:row.skills,review:Boolean(row.review),contentStatus:'structured-v1'}));row.skills.forEach((code,index)=>{const sid=skillId(db,code);if(!sid)throw new Error(`missing skill ${code}`);link.run(lid,sid,row.review?'review':index===0?'primary':'supporting',index+1);});for(const [locale,lang] of [['en',row.en],['es',row.es]])loc.run(lid,locale,lang[0],lang[1],JSON.stringify(localizedContent(lang)));}})();
  return {lessons:all.length,foundations:foundations.length,development:development.length,locales:['en','es']};
}

export function course0800Overview(db,locale='en'){
  const lang=locale==='es'?'es':'en';
  return db.prepare(`SELECT l.id,COALESCE(cl.title,l.title) AS title,COALESCE(cl.objective,l.objective) AS objective,l.content_json AS metaJson,cl.content_json AS localizedJson FROM lessons l JOIN lesson_skills ls ON ls.lesson_id=l.id AND ls.sequence_no=1 JOIN curriculum_skills cs ON cs.id=ls.skill_id JOIN curriculum_tracks t ON t.id=cs.track_id LEFT JOIN curriculum_localizations cl ON cl.entity_type='lesson' AND cl.entity_id=l.id AND cl.locale=? WHERE t.framework_id=? AND t.code IN (?,?) AND l.id LIKE 'LESSON-HMENA-%' ORDER BY t.sequence_no,CAST(substr(l.id,-2) AS INTEGER)`).all(lang,HMENA_FRAMEWORK_ID,F,D).map(r=>({...r,meta:JSON.parse(r.metaJson||'{}'),content:JSON.parse(r.localizedJson||'{}')}));
}
