import {randomUUID} from 'node:crypto';
import {openDatabase,listPlayers,loadSeries} from './db.js';
import {activityStatus,dailyPace} from './league-engine.js';
import {LichessClient,lichessRating} from './providers/lichess.js';
import {ChessComClient,chessComRating} from './providers/chesscom.js';
import {appendRows} from './services/sheets.js';
import {sendGroupMessage} from './services/whatsapp.js';
const db=openDatabase();const lichess=new LichessClient();let chesscom;try{chesscom=new ChessComClient();}catch{chesscom=null;}const now=new Date();const players=listPlayers(db,{registeredOnly:true});const ratingRows=[];
for(const player of players){try{let snapshot;if(player.platform==='lichess'){snapshot=lichessRating(await lichess.getUser(player.username));}else if(player.platform==='chesscom'&&chesscom){snapshot=chessComRating(await chesscom.getStats(player.username));}if(snapshot?.rating!=null){db.prepare('INSERT INTO rating_snapshots (player_id,platform,rating,rating_type,captured_at) VALUES (?,?,?,?,?)').run(player.id,player.platform,snapshot.rating,snapshot.type,now.toISOString());ratingRows.push([`RS-${randomUUID().slice(0,8)}`,player.id,player.platform,player.username,snapshot.rating,snapshot.type,now.toISOString(),'','','API']);}}catch(error){console.error(`rating refresh failed for ${player.username}:`,error.message);}}
if(ratingRows.length)await appendRows('Ratings!A:J',ratingRows);
const remainingByPlayer=new Map();for(const item of loadSeries(db).filter(s=>s.status!=='COMPLETE')){const remaining=Math.max(0,item.gamesRequired-item.gamesPlayed);remainingByPlayer.set(item.player1Id,(remainingByPlayer.get(item.player1Id)||0)+remaining);remainingByPlayer.set(item.player2Id,(remainingByPlayer.get(item.player2Id)||0)+remaining);}
const daysRemaining=Math.max(1,Number(process.env.SEASON_DAYS_REMAINING||process.env.SEASON_MAX_DAYS||players.length||1));const due=[];
for(const player of players){const remainingGames=remainingByPlayer.get(player.id)||0;if(!remainingGames)continue;const activity=activityStatus(player.last_activity_at,now);const target=dailyPace(remainingGames,daysRemaining);if(['REMINDER','URGENT','OVERDUE','NO_ACTIVITY'].includes(activity.status)){const today=now.toISOString().slice(0,10);const key=`${today}:${player.id}:${activity.status}`;const already=db.prepare('SELECT 1 FROM notifications WHERE kind=? AND player_id=? LIMIT 1').get(key,player.id);if(!already){const message=`${player.name}: ${activity.status}; ${remainingGames} partidas pendientes; ritmo recomendado ${target}/día.`;db.prepare(`INSERT INTO notifications (player_id,channel,kind,message,status,scheduled_for) VALUES (?,'WhatsApp',?,?,'PENDING',?)`).run(player.id,key,message,now.toISOString());due.push(message);}}}
if(due.length){const text=`⏰ HMENA Chess League — actividad\n\n${due.map(x=>`• ${x}`).join('\n')}\n\nPuedes adelantar partidas contra cualquier rival pendiente que esté disponible.`;try{const result=await sendGroupMessage(text);if(!result?.skipped)db.prepare("UPDATE notifications SET status='SENT', sent_at=? WHERE status='PENDING' AND scheduled_for<=?").run(now.toISOString(),now.toISOString());}catch(error){console.error('WhatsApp digest failed:',error.message);}}
console.log(JSON.stringify({refreshedRatings:ratingRows.length,reminders:due.length,at:now.toISOString()}));
